vti_encoding:SR|utf8-nl
vti_author:SR|AD-INS\\luwis
vti_modifiedby:SR|AD-INS\\luwis
vti_timelastmodified:TR|06 Sep 2008 10:41:15 -0000
vti_timecreated:TR|06 Sep 2008 10:19:35 -0000
vti_title:SR|Untitled Document
vti_extenderversion:SR|12.0.0.4518
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|06 Sep 2008 10:41:15 -0000
vti_cacheddtm:TX|06 Sep 2008 10:40:51 -0000
vti_filesize:IR|2939
vti_cachedtitle:SR|Untitled Document
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|Q|../../Confins.css S|../../images/butkiri1.gif S|../../images/butkiri.gif S|../../images/butkanan.gif S|../../images/butkanan1.gif S|../../images/butgo.gif
vti_cachedsvcrellinks:VX|FQUS|Confins.css FSUS|images/butkiri1.gif FSUS|images/butkiri.gif FSUS|images/butkanan.gif FSUS|images/butkanan1.gif FSUS|images/butgo.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|iso-8859-1
