vti_encoding:SR|utf8-nl
vti_author:SR|AD-INS\\luwis
vti_modifiedby:SR|AD-INS\\luwis
vti_timelastmodified:TR|06 Sep 2008 10:39:39 -0000
vti_timecreated:TR|06 Sep 2008 10:32:03 -0000
vti_title:SR|Untitled Document
vti_extenderversion:SR|12.0.0.4518
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|06 Sep 2008 10:39:12 -0000
vti_cacheddtm:TX|06 Sep 2008 10:39:12 -0000
vti_filesize:IR|4516
vti_cachedtitle:SR|Untitled Document
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|Q|../../Confins.css H|../FundingSourceView.htm H|../FundingSourceContractView.htm H|../DrawdownView.htm S|../../Images/iconcalendar.gif H|javascript:history.go(-1); S|../../Images/ButtonSave.gif S|../../Images/ButtonCancel.gif
vti_cachedsvcrellinks:VX|FQUS|Confins.css FHUS|ChannelSecurity/FundingSourceView.htm FHUS|ChannelSecurity/FundingSourceContractView.htm FHUS|ChannelSecurity/DrawdownView.htm FSUS|Images/iconcalendar.gif SHUS|javascript:history.go(-1); FSUS|Images/ButtonSave.gif FSUS|Images/ButtonCancel.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|iso-8859-1
