vti_encoding:SR|utf8-nl
vti_author:SR|AD-INS\\luwis
vti_modifiedby:SR|AD-INS\\luwis
vti_timelastmodified:TR|11 Sep 2008 12:00:09 -0000
vti_timecreated:TR|11 Sep 2008 11:50:58 -0000
vti_title:SR|Untitled Document
vti_extenderversion:SR|12.0.0.4518
vti_backlinkinfo:VX|
vti_nexttolasttimemodified:TW|11 Sep 2008 12:00:09 -0000
vti_cacheddtm:TX|11 Sep 2008 12:00:00 -0000
vti_filesize:IR|10002
vti_cachedtitle:SR|Untitled Document
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|Q|../../Confins.css S|../../images/butkiri1.gif S|../../images/butkiri.gif S|../../images/butkanan.gif S|../../images/butkanan1.gif S|../../images/butgo.gif H|javascript:window.close(); S|../../Images/ButtonClose.gif
vti_cachedsvcrellinks:VX|FQUS|Confins.css FSUS|images/butkiri1.gif FSUS|images/butkiri.gif FSUS|images/butkanan.gif FSUS|images/butkanan1.gif FSUS|images/butgo.gif SHUS|javascript:window.close(); FSUS|Images/ButtonClose.gif
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_metatags:VR|HTTP-EQUIV=Content-Type text/html;\\ charset=iso-8859-1
vti_charset:SR|iso-8859-1
