<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>
<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 11">
<link rel=File-List href="ReportAssetMaster_files/filelist.xml">
<link rel=Edit-Time-Data href="ReportAssetMaster_files/editdata.mso">
<link rel=OLE-Object-Data href="ReportAssetMaster_files/oledata.mso">
<!--[if gte mso 9]><xml>
 <o:DocumentProperties>
  <o:LastAuthor>Jessy</o:LastAuthor>
  <o:Created>2007-04-25T09:58:40Z</o:Created>
  <o:LastSaved>2007-04-25T10:06:53Z</o:LastSaved>
  <o:Version>11.5606</o:Version>
 </o:DocumentProperties>
</xml><![endif]-->
<style>
<!--table
	{mso-displayed-decimal-separator:"\.";
	mso-displayed-thousand-separator:"\,";}
@page
	{margin:1.0in .75in 1.0in .75in;
	mso-header-margin:.5in;
	mso-footer-margin:.5in;}
tr
	{mso-height-source:auto;}
col
	{mso-width-source:auto;}
br
	{mso-data-placement:same-cell;}
.style0
	{mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	white-space:nowrap;
	mso-rotate:0;
	mso-background-source:auto;
	mso-pattern:auto;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	border:none;
	mso-protection:locked visible;
	mso-style-name:Normal;
	mso-style-id:0;}
td
	{mso-style-parent:style0;
	padding-top:1px;
	padding-right:1px;
	padding-left:1px;
	mso-ignore:padding;
	color:windowtext;
	font-size:10.0pt;
	font-weight:400;
	font-style:normal;
	text-decoration:none;
	font-family:Arial;
	mso-generic-font-family:auto;
	mso-font-charset:0;
	mso-number-format:General;
	text-align:general;
	vertical-align:bottom;
	border:none;
	mso-background-source:auto;
	mso-pattern:auto;
	mso-protection:locked visible;
	white-space:nowrap;
	mso-rotate:0;}
.xl24
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;}
.xl25
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	text-align:center;}
.xl26
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
.xl27
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	white-space:normal;}
.xl28
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	border-top:none;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;
	white-space:normal;}
.xl29
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	text-align:left;}
.xl30
	{mso-style-parent:style0;
	font-size:8.0pt;
	font-family:"Courier New", monospace;
	mso-font-charset:0;
	border-top:.5pt solid windowtext;
	border-right:none;
	border-bottom:.5pt solid windowtext;
	border-left:none;}
-->
</style>
<!--[if gte mso 9]><xml>
 <x:ExcelWorkbook>
  <x:ExcelWorksheets>
   <x:ExcelWorksheet>
    <x:Name>AssetMaster</x:Name>
    <x:WorksheetOptions>
     <x:Selected/>
     <x:DoNotDisplayGridlines/>
     <x:Panes>
      <x:Pane>
       <x:Number>3</x:Number>
       <x:ActiveRow>18</x:ActiveRow>
       <x:ActiveCol>3</x:ActiveCol>
      </x:Pane>
     </x:Panes>
     <x:ProtectContents>False</x:ProtectContents>
     <x:ProtectObjects>False</x:ProtectObjects>
     <x:ProtectScenarios>False</x:ProtectScenarios>
    </x:WorksheetOptions>
   </x:ExcelWorksheet>
  </x:ExcelWorksheets>
  <x:WindowHeight>10365</x:WindowHeight>
  <x:WindowWidth>17100</x:WindowWidth>
  <x:WindowTopX>120</x:WindowTopX>
  <x:WindowTopY>75</x:WindowTopY>
  <x:ProtectStructure>False</x:ProtectStructure>
  <x:ProtectWindows>False</x:ProtectWindows>
 </x:ExcelWorkbook>
</xml><![endif]-->
</head>

<body link=blue vlink=purple>
<!--The following information was generated by Microsoft Excel's Publish as Web
Page wizard.--><!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.--><!-----------------------------><!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD --><!----------------------------->

<table x:str border=0 cellpadding=0 cellspacing=0 width=788 style='border-collapse:
 collapse;table-layout:fixed;width:591pt'>
 <col class=xl24 width=171 style='mso-width-source:userset;mso-width-alt:6253;
 width:128pt'>
 <col class=xl24 width=32 style='mso-width-source:userset;mso-width-alt:1170;
 width:24pt'>
 <col class=xl24 width=152 style='mso-width-source:userset;mso-width-alt:5558;
 width:114pt'>
 <col class=xl24 width=120 style='mso-width-source:userset;mso-width-alt:4388;
 width:90pt'>
 <col class=xl24 width=0 style='display:none;mso-width-source:userset;
 mso-width-alt:658'>
 <col class=xl24 width=121 style='mso-width-source:userset;mso-width-alt:4425;
 width:91pt'>
 <col width=64 span=3 style='width:48pt'>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl24 width=171 style='height:12.75pt;width:128pt'>PT.
  XXXXX</td>
  <td colspan=2 class=xl25 width=184 style='width:138pt'>ASSET MASTER</td>
  <td class=xl24 width=120 style='width:90pt'></td>
  <td class=xl24 width=0></td>
  <td class=xl24 width=121 style='width:91pt'></td>
  <td colspan=3 class=xl29 width=192 style='width:144pt'>Report Id :
  RptAssetMaster</td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl24 style='height:12.75pt'>Asset Type : Motorcycle</td>
  <td colspan=2 class=xl25>Date : dd/mm/yyyy</td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
  <td colspan=3 class=xl29>Page n of m</td>
 </tr>
 <tr class=xl24 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td height=15 colspan=2 class=xl24 style='height:11.25pt;mso-ignore:colspan'></td>
  <td class=xl25></td>
  <td colspan=6 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td colspan=5 height=15 class=xl29 style='height:11.25pt'></td>
  <td colspan=4 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl30 style='height:12.75pt'>Asset Code</td>
  <td colspan=2 class=xl30>Description</td>
  <td class=xl30>Asset Category</td>
  <td class=xl30>&nbsp;</td>
  <td class=xl30>Resale Value (%)</td>
  <td class=xl30>&nbsp;</td>
  <td class=xl30>&nbsp;</td>
  <td class=xl30>&nbsp;</td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 width=171 style='height:12.75pt;width:128pt'>HONDA</td>
  <td colspan=2 class=xl24>Honda</td>
  <td colspan=6 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 width=171 style='height:12.75pt;width:128pt'>HONDA.SUPRA</td>
  <td colspan=2 class=xl24>Honda - Supra</td>
  <td colspan=6 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl28 width=171 style='height:12.75pt;width:128pt'>HONDA.SUPRA.FIT</td>
  <td colspan=2 class=xl26>Honda - Supra - Fit</td>
  <td class=xl26>Bebek</td>
  <td class=xl26>&nbsp;</td>
  <td class=xl26 align=right x:num>0</td>
  <td class=xl26>&nbsp;</td>
  <td class=xl26>&nbsp;</td>
  <td class=xl26>&nbsp;</td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 style='height:12.75pt'></td>
  <td colspan=8 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 style='height:12.75pt'></td>
  <td colspan=8 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 style='height:12.75pt'></td>
  <td colspan=8 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=17 style='mso-height-source:userset;height:12.75pt'>
  <td height=17 class=xl27 style='height:12.75pt'></td>
  <td colspan=8 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td height=15 class=xl24 style='height:11.25pt' x:str="Filter By    : ">Filter
  By<span style='mso-spacerun:yes'>    </span>:<span
  style='mso-spacerun:yes'> </span></td>
  <td colspan=8 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td colspan=2 height=15 class=xl24 style='height:11.25pt'>Printed Date :
  dd/mm/yyyy</td>
  <td colspan=7 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <tr class=xl24 height=15 style='mso-height-source:userset;height:11.25pt'>
  <td colspan=2 height=15 class=xl24 style='height:11.25pt'>Printed By<span
  style='mso-spacerun:yes'>   </span>: xxxx10xxxx</td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
  <td class=xl24><!-----------------------------><!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD--><!-----------------------------></td>
  <td colspan=3 class=xl24 style='mso-ignore:colspan'></td>
 </tr>
 <![if supportMisalignedColumns]>
 <tr height=0 style='display:none'>
  <td width=171 style='width:128pt'></td>
  <td width=32 style='width:24pt'></td>
  <td width=152 style='width:114pt'></td>
  <td width=120 style='width:90pt'></td>
  <td width=0></td>
  <td width=121 style='width:91pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
  <td width=64 style='width:48pt'></td>
 </tr>
 <![endif]>
</table>

</body>

</html>
