<%@ Page Language="VB" ContentType="text/html" ResponseEncoding="iso-8859-1" %>
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="../../Confins.css" rel="stylesheet" type="text/css">
<script language="JavaScript" type="text/JavaScript">
<!--
function MM_openBrWindow(theURL,winName,features) { //v2.0
  window.open(theURL,winName,features);
}
//-->
</script>
</head>
<body>
<form runat="server" id="FrmBucketEdit">
<div align="center">
  <table width="95%" border="0" cellpadding="0" cellspacing="0">
    <tr> 
      <td colspan="3">&nbsp;</td>
    </tr>
  </table>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr class="trtopikuning"> 
      <td width="10" height="20" class="tdtopihijaukiri">&nbsp;</td>
      <td align="center" class="tdtopihijau">VIEW ADDITIONAL COLLATERAL - 
		RELEASE</td>
      <td width="10" class="tdtopihijaukanan">&nbsp;</td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
   	<tr>
      <td width="25%" class="tdgenap" style="height: 24px">Name</td>
      <td width="78%" class="tdganjil" style="height: 24px"> 
        xxxxxxxx50xxxxxxxx</td>
    </tr>
	

  </table>
  <br>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr class="trtopikuning"> 
      <td width="10" height="20" class="tdtopihijaukiri">&nbsp;</td>
      <td align="center" class="tdtopihijau">CUSTOMER EXPOSURE DATA</td>
      <td width="10" class="tdtopihijaukanan">&nbsp;</td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="3" cellspacing="1" class="tablegrid">
    <tr> 
      <td width="50%" align="center" class="tdjudulhijau"><div align="left">MAXIMUM 
          AMOUNT</div></td>
      <td align="center" class="tdjudulhijau"><div align="left">OUTSTANDING AMOUNT</div></td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
    <tr> 
      <td width="25%" class="tdgenap">Max Outstanding Balance</td>
      <td width="25%" align="right" class="tdganjil">999,999,999.99</td>
      <td width="25%" class="tdgenap">Outstanding Balance</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap">Max Installment Amount</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap">Outstanding Installment </td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td width="24%" class="tdgenap">Max Overdue Amount </td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap">Outstanding Principal</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap"> Max Overdue Days</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap">Outstanding Interest</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="3" cellspacing="1" class="tablegrid">
    <tr> 
      <td align="center" class="tdjudulhijau"><div align="left">NUMBER OF</div>
        <div align="left"></div></td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
    <tr> 
      <td width="25%" class="tdgenap">Active Agreement</td>
      <td width="25%" align="right" class="tdganjil"><div align="left">99</div></td>
      <td width="25%" class="tdgenap">Repossed Asset</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
    </tr>
    <tr> 
      <td class="tdgenap">In Process Agreement</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
      <td class="tdgenap">Inventoried Asset</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
    </tr>
    <tr> 
      <td class="tdgenap">Asset in Financing</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
      <td class="tdgenap">Written Off Agreement</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
    </tr>
    <tr> 
      <td class="tdgenap"> Rejected Agreement</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
      <td class="tdgenap">Non Accrual Agreement</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
    </tr>
    <tr> 
      <td class="tdgenap"> Cancelled Agreement</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
      <td class="tdgenap">Bounce Cheque</td>
      <td align="right" class="tdganjil"><div align="left">99</div></td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
    <tr class="tdjudulhijau"> 
      <td width="25%">BUCKET</td>
      <td width="25%" align="right"><div align="center">TOTAL PAST DUE</div></td>
      <td width="25%">BUCKET</td>
      <td align="right"><div align="center">TOTAL PAST DUE</div></td>
    </tr>
    <tr> 
      <td class="tdgenap">Bucket 1</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap">Bucket 6</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap">Bucket 2</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap">Bucket 7</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap"> Bucket 3</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap"> Bucket 8</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap"> Bucket 4</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap"> Bucket 9</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap"> Bucket 5</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
      <td class="tdgenap"> Bucket 10</td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
    <tr> 
      <td class="tdgenap">&nbsp;</td>
      <td align="right" class="tdganjil">&nbsp;</td>
      <td class="tdgenap"><strong>TOTAL</strong></td>
      <td align="right" class="tdganjil">999,999,999.99</td>
    </tr>
  </table>

  <br>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr class="trtopikuning"> 
      <td width="10" height="20" class="tdtopihijaukiri">&nbsp;</td>
      <td align="center" class="tdtopihijau">ASSET ADDITIONAL COLLATERAL - 
		RELEASE</td>
      <td width="10" class="tdtopihijaukanan">&nbsp;</td>
    </tr>
  </table>

   
    <div align="center"> 
      <asp:GridView runat="server" id="GrdViewBranch" AutoGenerateColumns="False" DataSourceID="XmlDataSource1" CellPadding="2" Width="95%" AllowSorting="True">
		<Columns>
			<asp:boundfield DataField="valstring3" SortExpression="valstring3" HeaderText="ASSET NO">
			</asp:boundfield>
			<asp:boundfield DataField="valstring10" HeaderText="ASSET TYPE">
				<ItemStyle HorizontalAlign="Center" />
			</asp:boundfield>
			<asp:templatefield HeaderText="ASSET DESCRIPTION">
				<AlternatingItemTemplate>
					<asp:HyperLink runat="server" id="lnkAgreementNo" NavigateUrl="MarketingEmployeeInternalView.aspx" Target="_blank">xxxxxxxx50xxxxxxxx
					</asp:HyperLink>
				</AlternatingItemTemplate>
				<ItemStyle HorizontalAlign="Left" />
				<ItemTemplate>
					<asp:HyperLink runat="server" id="lnkAgreementNo" NavigateUrl="MarketingEmployeeExternalView.aspx" Target="_blank">xxxxxxxx50xxxxxxxx
					</asp:HyperLink>
				</ItemTemplate>
			</asp:templatefield>
			<asp:boundfield DataField="valdate" HeaderText="REMINDER INSURANCE DATE">
				<ItemStyle HorizontalAlign="Left" />
			</asp:boundfield>
			<asp:boundfield DataField="valamount" SortExpression="valamount" HeaderText="MARKET VALUE">
				<ItemStyle HorizontalAlign="Right" />
			</asp:boundfield>
			<asp:boundfield DataField="vRate" SortExpression="vRate" HeaderText="RESALE VALUE (%)">
				<ItemStyle HorizontalAlign="Right" />
			</asp:boundfield>
		</Columns>
		<HeaderStyle CssClass="tdjudulhijau" />
		<AlternatingRowStyle CssClass="tdgenap" />
		</asp:GridView>

  
  
  
  
  <table width="95%" height="25" border="0" align="center" cellpadding="0" cellspacing="0">
    <tr> 
      <td width="30" align="center">
		<img src="../../images/butkiri1.gif" width="20" height="20"></td>
      <td width="30" align="center">
		<img src="../../images/butkiri.gif" width="20" height="20"></td>
      <td width="30" align="center">
		<img src="../../images/butkanan.gif" width="20" height="20"></td>
      <td width="30" align="center">
		<img src="../../images/butkanan1.gif" width="20" height="20"></td>
      <td width="130" align="center">Page 
        <input type="text" name="textfield222" class="inptype" size="3"> &nbsp; 
        <img src="../../images/butgo.gif" width="30" height="25" align="absmiddle"></td>
      <td align="right"><font color="#999999">Page x of y, Total x record(s)</font></td>
    </tr>
  </table>
		<asp:XmlDataSource runat="server" id="XmlDataSource2">
		</asp:XmlDataSource>
  
  <br>
  
     <asp:XmlDataSource runat="server" ID="XmlDataSource1" DataFile="../../DataType.xml">
	</asp:XmlDataSource>


 </div>
 

  <br>
	<table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr> 
      <td width="50%" height="30">&nbsp;</td>
      <td width="50%" align="right">
		<a href="javascript:window.close();"><img src="../../Images/ButtonClose.gif" width="100" height="20" border="0"></a>      </td>
    </tr>
  </table>
</div>
</form>
</body>
</html>
