package com.adibrata.smartdealer.model;
// Generated Jul 18, 2015 2:53:38 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountPayable generated by hbm2java
 */
@Entity
@Table(name = "AccountPayable", catalog = "SmartDealer")
public class AccountPayable implements java.io.Serializable
{

	private String accNameTo;
	private String accNoTo;
	private Double apamount;
	private Date apdate;
	private Double apdisburse;
	private String apno;
	private String apstatus;
	private String apto;
	private String aptype;
	private String bankBranchTo;
	private String bankMasterTo;
	private long currencyId;
	private double currencyRate;
	private String description;
	private Date dtmCrt;
	private Date dtmUpd;
	private Date dueDate;
	private long id;
	private Office officeByOfficeDisbId;
	private Office officeByOfficeId;
	private Partner partner;
	private Set<Pvdetail> pvdetails = new HashSet<Pvdetail>(0);
	private String referenceNo;
	private String usrCrt;
	private String usrUpd;

	public AccountPayable()
		{
		}

	public AccountPayable(long id, Office officeByOfficeId,
			Office officeByOfficeDisbId, Partner partner, String apno,
			String aptype, String apstatus, Date apdate,
			String referenceNo, String description, Date dueDate,
			long currencyId, double currencyRate, Double apamount,
			Double apdisburse, String apto, String accNameTo,
			String accNoTo, String bankMasterTo, String bankBranchTo,
			String usrCrt, Date dtmUpd, String usrUpd, Date dtmCrt,
			Set<Pvdetail> pvdetails)
		{
			this.id = id;
			this.officeByOfficeId = officeByOfficeId;
			this.officeByOfficeDisbId = officeByOfficeDisbId;
			this.partner = partner;
			this.apno = apno;
			this.aptype = aptype;
			this.apstatus = apstatus;
			this.apdate = apdate;
			this.referenceNo = referenceNo;
			this.description = description;
			this.dueDate = dueDate;
			this.currencyId = currencyId;
			this.currencyRate = currencyRate;
			this.apamount = apamount;
			this.apdisburse = apdisburse;
			this.apto = apto;
			this.accNameTo = accNameTo;
			this.accNoTo = accNoTo;
			this.bankMasterTo = bankMasterTo;
			this.bankBranchTo = bankBranchTo;
			this.usrCrt = usrCrt;
			this.dtmUpd = dtmUpd;
			this.usrUpd = usrUpd;
			this.dtmCrt = dtmCrt;
			this.pvdetails = pvdetails;
		}
	public AccountPayable(long id, String referenceNo, String description,
			long currencyId, double currencyRate, String apto,
			String accNameTo, String accNoTo, String bankMasterTo,
			String bankBranchTo)
		{
			this.id = id;
			this.referenceNo = referenceNo;
			this.description = description;
			this.currencyId = currencyId;
			this.currencyRate = currencyRate;
			this.apto = apto;
			this.accNameTo = accNameTo;
			this.accNoTo = accNoTo;
			this.bankMasterTo = bankMasterTo;
			this.bankBranchTo = bankBranchTo;
		}

	@Column(name = "AccNameTo", nullable = false, length = 50)
	public String getAccNameTo()
		{
			return this.accNameTo;
		}

	@Column(name = "AccNoTo", nullable = false, length = 50)
	public String getAccNoTo()
		{
			return this.accNoTo;
		}

	@Column(name = "APAmount", precision = 53, scale = 0)
	public Double getApamount()
		{
			return this.apamount;
		}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "APDate", length = 23)
	public Date getApdate()
		{
			return this.apdate;
		}

	@Column(name = "APDisburse", precision = 53, scale = 0)
	public Double getApdisburse()
		{
			return this.apdisburse;
		}

	@Column(name = "APNo", length = 50)
	public String getApno()
		{
			return this.apno;
		}

	@Column(name = "APStatus", length = 2)
	public String getApstatus()
		{
			return this.apstatus;
		}

	@Column(name = "APTo", nullable = false, length = 50)
	public String getApto()
		{
			return this.apto;
		}

	@Column(name = "APType", length = 5)
	public String getAptype()
		{
			return this.aptype;
		}

	@Column(name = "BankBranchTo", nullable = false, length = 50)
	public String getBankBranchTo()
		{
			return this.bankBranchTo;
		}

	@Column(name = "BankMasterTo", nullable = false, length = 50)
	public String getBankMasterTo()
		{
			return this.bankMasterTo;
		}

	@Column(name = "CurrencyID", nullable = false)
	public long getCurrencyId()
		{
			return this.currencyId;
		}

	@Column(name = "CurrencyRate", nullable = false, precision = 53, scale = 0)
	public double getCurrencyRate()
		{
			return this.currencyRate;
		}

	@Column(name = "Description", nullable = false, length = 200)
	public String getDescription()
		{
			return this.description;
		}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmCrt", length = 16)
	public Date getDtmCrt()
		{
			return this.dtmCrt;
		}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmUpd", length = 16)
	public Date getDtmUpd()
		{
			return this.dtmUpd;
		}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DueDate", length = 23)
	public Date getDueDate()
		{
			return this.dueDate;
		}

	@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "Id", unique = true, nullable = false)
	public long getId()
		{
			return this.id;
		}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OfficeDisbId")
	public Office getOfficeByOfficeDisbId()
		{
			return this.officeByOfficeDisbId;
		}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OfficeId")
	public Office getOfficeByOfficeId()
		{
			return this.officeByOfficeId;
		}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PartnerCode")
	public Partner getPartner()
		{
			return this.partner;
		}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountPayable")
	public Set<Pvdetail> getPvdetails()
	{
		return this.pvdetails;
	}

	@Column(name = "ReferenceNo", nullable = false, length = 20)
	public String getReferenceNo()
		{
			return this.referenceNo;
		}

	@Column(name = "UsrCrt", length = 50)
	public String getUsrCrt()
		{
			return this.usrCrt;
		}

	@Column(name = "UsrUpd", length = 50)
	public String getUsrUpd()
		{
			return this.usrUpd;
		}

	public void setAccNameTo(String accNameTo)
		{
			this.accNameTo = accNameTo;
		}

	public void setAccNoTo(String accNoTo)
		{
			this.accNoTo = accNoTo;
		}

	public void setApamount(Double apamount)
		{
			this.apamount = apamount;
		}

	public void setApdate(Date apdate)
		{
			this.apdate = apdate;
		}

	public void setApdisburse(Double apdisburse)
		{
			this.apdisburse = apdisburse;
		}

	public void setApno(String apno)
		{
			this.apno = apno;
		}

	public void setApstatus(String apstatus)
		{
			this.apstatus = apstatus;
		}

	public void setApto(String apto)
		{
			this.apto = apto;
		}

	public void setAptype(String aptype)
		{
			this.aptype = aptype;
		}

	public void setBankBranchTo(String bankBranchTo)
		{
			this.bankBranchTo = bankBranchTo;
		}

	public void setBankMasterTo(String bankMasterTo)
		{
			this.bankMasterTo = bankMasterTo;
		}

	public void setCurrencyId(long currencyId)
		{
			this.currencyId = currencyId;
		}

	public void setCurrencyRate(double currencyRate)
		{
			this.currencyRate = currencyRate;
		}

	public void setDescription(String description)
		{
			this.description = description;
		}

	public void setDtmCrt(Date dtmCrt)
		{
			this.dtmCrt = dtmCrt;
		}

	public void setDtmUpd(Date dtmUpd)
		{
			this.dtmUpd = dtmUpd;
		}

	public void setDueDate(Date dueDate)
		{
			this.dueDate = dueDate;
		}

	public void setId(long id)
		{
			this.id = id;
		}

	public void setOfficeByOfficeDisbId(Office officeByOfficeDisbId)
		{
			this.officeByOfficeDisbId = officeByOfficeDisbId;
		}

	public void setOfficeByOfficeId(Office officeByOfficeId)
		{
			this.officeByOfficeId = officeByOfficeId;
		}

	public void setPartner(Partner partner)
		{
			this.partner = partner;
		}

	public void setPvdetails(Set<Pvdetail> pvdetails)
		{
			this.pvdetails = pvdetails;
		}

	public void setReferenceNo(String referenceNo)
		{
			this.referenceNo = referenceNo;
		}

	public void setUsrCrt(String usrCrt)
		{
			this.usrCrt = usrCrt;
		}

	public void setUsrUpd(String usrUpd)
		{
			this.usrUpd = usrUpd;
		}

}
