package com.adibrata.smartdealer.model;
// Generated Jul 16, 2015 1:10:05 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agrmnt generated by hbm2java
 */
@Entity
@Table(name = "Agrmnt", schema = "dbo", catalog = "SmartDealer")
public class Agrmnt implements java.io.Serializable {

	private long id;
	private Application application;
	private Customer customer;
	private Office office;
	private Partner partner;
	private String agrmntCode;
	private Date dtmUpd;
	private String usrUpd;
	private Date dtmCrt;
	private String usrCrt;
	private Set<AgrmntMnt> agrmntMnts = new HashSet<AgrmntMnt>(0);
	private Set<InstSchedule> instSchedules = new HashSet<InstSchedule>(0);
	private Set<AgrmntColl> agrmntColls = new HashSet<AgrmntColl>(0);
	private Set<AgrmntInsurance> agrmntInsurances = new HashSet<AgrmntInsurance>(
			0);

	public Agrmnt() {
	}

	public Agrmnt(long id) {
		this.id = id;
	}
	public Agrmnt(long id, Application application, Customer customer,
			Office office, Partner partner, String agrmntCode, Date dtmUpd,
			String usrUpd, Date dtmCrt, String usrCrt,
			Set<AgrmntMnt> agrmntMnts, Set<InstSchedule> instSchedules,
			Set<AgrmntColl> agrmntColls, Set<AgrmntInsurance> agrmntInsurances) {
		this.id = id;
		this.application = application;
		this.customer = customer;
		this.office = office;
		this.partner = partner;
		this.agrmntCode = agrmntCode;
		this.dtmUpd = dtmUpd;
		this.usrUpd = usrUpd;
		this.dtmCrt = dtmCrt;
		this.usrCrt = usrCrt;
		this.agrmntMnts = agrmntMnts;
		this.instSchedules = instSchedules;
		this.agrmntColls = agrmntColls;
		this.agrmntInsurances = agrmntInsurances;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AppId")
	public Application getApplication() {
		return this.application;
	}

	public void setApplication(Application application) {
		this.application = application;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CustomerId")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "OfficeId")
	public Office getOffice() {
		return this.office;
	}

	public void setOffice(Office office) {
		this.office = office;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PartnerCode")
	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	@Column(name = "AgrmntCode", length = 20)
	public String getAgrmntCode() {
		return this.agrmntCode;
	}

	public void setAgrmntCode(String agrmntCode) {
		this.agrmntCode = agrmntCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmUpd", length = 16)
	public Date getDtmUpd() {
		return this.dtmUpd;
	}

	public void setDtmUpd(Date dtmUpd) {
		this.dtmUpd = dtmUpd;
	}

	@Column(name = "UsrUpd", length = 50)
	public String getUsrUpd() {
		return this.usrUpd;
	}

	public void setUsrUpd(String usrUpd) {
		this.usrUpd = usrUpd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DtmCrt", length = 16)
	public Date getDtmCrt() {
		return this.dtmCrt;
	}

	public void setDtmCrt(Date dtmCrt) {
		this.dtmCrt = dtmCrt;
	}

	@Column(name = "UsrCrt", length = 50)
	public String getUsrCrt() {
		return this.usrCrt;
	}

	public void setUsrCrt(String usrCrt) {
		this.usrCrt = usrCrt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
	public Set<AgrmntMnt> getAgrmntMnts() {
		return this.agrmntMnts;
	}

	public void setAgrmntMnts(Set<AgrmntMnt> agrmntMnts) {
		this.agrmntMnts = agrmntMnts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
	public Set<InstSchedule> getInstSchedules() {
		return this.instSchedules;
	}

	public void setInstSchedules(Set<InstSchedule> instSchedules) {
		this.instSchedules = instSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
	public Set<AgrmntColl> getAgrmntColls() {
		return this.agrmntColls;
	}

	public void setAgrmntColls(Set<AgrmntColl> agrmntColls) {
		this.agrmntColls = agrmntColls;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
	public Set<AgrmntInsurance> getAgrmntInsurances() {
		return this.agrmntInsurances;
	}

	public void setAgrmntInsurances(Set<AgrmntInsurance> agrmntInsurances) {
		this.agrmntInsurances = agrmntInsurances;
	}

}
