
package com.adibrata.smartdealer.model;
// Generated Jul 21, 2015 2:35:33 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgrmntInsurance generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "AgrmntInsurance", catalog = "SmartDealer")
public class AgrmntInsurance implements java.io.Serializable
	{
		
		private long id;
		private Agrmnt agrmnt;
		private Long appId;
		private Long currencyId;
		private Long insuranceCoyId;
		private Long insuranceCoyBranchId;
		private String applicationType;
		private double mainPremiumToCust;
		private double loadingFeeToCust;
		private double tpltoCust;
		private double floodToCust;
		private double srcctoCust;
		private double premiumAmountByCustBeforeDisc;
		private double discToCustAmount;
		private double premiumAmountByCust;
		private double adminFeeToCust;
		private double meteraiFeeToCust;
		private double capitalizedAmount;
		private Date startDate;
		private Date endDate;
		private String policyNumber;
		private Date policyReceiveDate;
		private String policyReceiveBy;
		private String flagInsActivation;
		private String flagReNew;
		private String flagInsStatus;
		private Date sppadate;
		private String sppano;
		private String insuranceRateType;
		private double mainStdPremium;
		private double srccstdPremium;
		private double floodStdPremium;
		private double tplstdPremium;
		private double tplstdAmount;
		private double totalStdPremium;
		private double sumInsured;
		private double srcctoInsco;
		private double tpltoInsco;
		private double floodToInsCo;
		private double loadingFeeToInsCo;
		private double mainPremiumToInsCo;
		private double premiumAmountToInsCo;
		private Date insCoSelectionDate;
		private double sellingRate;
		private double sellingAmount;
		private double adminFee;
		private double meteraiFee;
		private double paidAmountToInsco;
		private double earnAmount;
		private String insNotes;
		private String accNotes;
		private Date requestDate;
		private Date insActivateDate;
		private short insLength;
		private String mainCoverage;
		private String additionalCoverage;
		private String endorsDocNo;
		private String bdendorsDocNo;
		private Date bdendorsDate;
		private String bdendorsPolicyNo;
		private Date bdendorsPolicyReceiveDate;
		private double endorsToInsCoPremium;
		private double endorsPaidToInsCo;
		private double endorsAdditionalPremium;
		private String flagClaimProcess;
		private Date lastClaimDate;
		private char flagDocStatus;
		private double paidAmountByCust;
		private Double waivedAmountByCust;
		private Date paidDate;
		private double lateCharges;
		private long accPayId;
		private String insuredBy;
		private String insurancePaidBy;
		private double claimAmount;
		private double paidClaimAmount;
		private int yearNum;
		private Date terminationDate;
		private String isChangeInsCo;
		private String changeInsCoReason;
		private String coverPeriod;
		private String renewalDocNo;
		private Date renewalDocDate;
		private Double premiumBaseForRefundSupp;
		private String invoiceNo;
		private Double invoiceAmount;
		private Date invoiceDate;
		private Date receivedInvoiceDate;
		private Date flagInsStatusDate;
		private Character sppaprintStatus;
		private boolean isValidCustomerName;
		private boolean isValidAddress;
		private boolean isValidInsurancePeriode;
		private boolean isValidInsLength;
		private boolean isValidNumOfAsset;
		private boolean isValid;
		private Double insCapitalizedAmount;
		private Double addCapitalizedAmount;
		private short isNewCover;
		private String batchId;
		private Date batchDate;
		private String generate;
		private String typeCorrectionCode;
		private Date confirmDate;
		private String usrCrt;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		
		public AgrmntInsurance()
			{
			}
			
		public AgrmntInsurance(long id, double mainPremiumToCust, double loadingFeeToCust, double tpltoCust, double floodToCust, double srcctoCust, double premiumAmountByCustBeforeDisc, double discToCustAmount, double premiumAmountByCust,
		        double adminFeeToCust, double meteraiFeeToCust, double capitalizedAmount, String policyNumber, String policyReceiveBy, String flagReNew, String flagInsStatus, String sppano, String insuranceRateType, double mainStdPremium,
		        double srccstdPremium, double floodStdPremium, double tplstdPremium, double tplstdAmount, double totalStdPremium, double sumInsured, double srcctoInsco, double tpltoInsco, double floodToInsCo, double loadingFeeToInsCo,
		        double mainPremiumToInsCo, double premiumAmountToInsCo, double sellingRate, double sellingAmount, double adminFee, double meteraiFee, double paidAmountToInsco, double earnAmount, String insNotes, String accNotes, short insLength,
		        String mainCoverage, String additionalCoverage, String endorsDocNo, String bdendorsDocNo, String bdendorsPolicyNo, double endorsToInsCoPremium, double endorsPaidToInsCo, double endorsAdditionalPremium, String flagClaimProcess,
		        char flagDocStatus, double paidAmountByCust, double lateCharges, long accPayId, double claimAmount, double paidClaimAmount, int yearNum, String isChangeInsCo, String changeInsCoReason, String coverPeriod, String renewalDocNo,
		        Double premiumBaseForRefundSupp, boolean isValidCustomerName, boolean isValidAddress, boolean isValidInsurancePeriode, boolean isValidInsLength, boolean isValidNumOfAsset, boolean isValid, short isNewCover)
			{
				this.id = id;
				this.mainPremiumToCust = mainPremiumToCust;
				this.loadingFeeToCust = loadingFeeToCust;
				this.tpltoCust = tpltoCust;
				this.floodToCust = floodToCust;
				this.srcctoCust = srcctoCust;
				this.premiumAmountByCustBeforeDisc = premiumAmountByCustBeforeDisc;
				this.discToCustAmount = discToCustAmount;
				this.premiumAmountByCust = premiumAmountByCust;
				this.adminFeeToCust = adminFeeToCust;
				this.meteraiFeeToCust = meteraiFeeToCust;
				this.capitalizedAmount = capitalizedAmount;
				this.policyNumber = policyNumber;
				this.policyReceiveBy = policyReceiveBy;
				this.flagReNew = flagReNew;
				this.flagInsStatus = flagInsStatus;
				this.sppano = sppano;
				this.insuranceRateType = insuranceRateType;
				this.mainStdPremium = mainStdPremium;
				this.srccstdPremium = srccstdPremium;
				this.floodStdPremium = floodStdPremium;
				this.tplstdPremium = tplstdPremium;
				this.tplstdAmount = tplstdAmount;
				this.totalStdPremium = totalStdPremium;
				this.sumInsured = sumInsured;
				this.srcctoInsco = srcctoInsco;
				this.tpltoInsco = tpltoInsco;
				this.floodToInsCo = floodToInsCo;
				this.loadingFeeToInsCo = loadingFeeToInsCo;
				this.mainPremiumToInsCo = mainPremiumToInsCo;
				this.premiumAmountToInsCo = premiumAmountToInsCo;
				this.sellingRate = sellingRate;
				this.sellingAmount = sellingAmount;
				this.adminFee = adminFee;
				this.meteraiFee = meteraiFee;
				this.paidAmountToInsco = paidAmountToInsco;
				this.earnAmount = earnAmount;
				this.insNotes = insNotes;
				this.accNotes = accNotes;
				this.insLength = insLength;
				this.mainCoverage = mainCoverage;
				this.additionalCoverage = additionalCoverage;
				this.endorsDocNo = endorsDocNo;
				this.bdendorsDocNo = bdendorsDocNo;
				this.bdendorsPolicyNo = bdendorsPolicyNo;
				this.endorsToInsCoPremium = endorsToInsCoPremium;
				this.endorsPaidToInsCo = endorsPaidToInsCo;
				this.endorsAdditionalPremium = endorsAdditionalPremium;
				this.flagClaimProcess = flagClaimProcess;
				this.flagDocStatus = flagDocStatus;
				this.paidAmountByCust = paidAmountByCust;
				this.lateCharges = lateCharges;
				this.accPayId = accPayId;
				this.claimAmount = claimAmount;
				this.paidClaimAmount = paidClaimAmount;
				this.yearNum = yearNum;
				this.isChangeInsCo = isChangeInsCo;
				this.changeInsCoReason = changeInsCoReason;
				this.coverPeriod = coverPeriod;
				this.renewalDocNo = renewalDocNo;
				this.premiumBaseForRefundSupp = premiumBaseForRefundSupp;
				this.isValidCustomerName = isValidCustomerName;
				this.isValidAddress = isValidAddress;
				this.isValidInsurancePeriode = isValidInsurancePeriode;
				this.isValidInsLength = isValidInsLength;
				this.isValidNumOfAsset = isValidNumOfAsset;
				this.isValid = isValid;
				this.isNewCover = isNewCover;
			}
			
		public AgrmntInsurance(long id, Agrmnt agrmnt, Long appId, Long currencyId, Long insuranceCoyId, Long insuranceCoyBranchId, String applicationType, double mainPremiumToCust, double loadingFeeToCust, double tpltoCust, double floodToCust,
		        double srcctoCust, double premiumAmountByCustBeforeDisc, double discToCustAmount, double premiumAmountByCust, double adminFeeToCust, double meteraiFeeToCust, double capitalizedAmount, Date startDate, Date endDate, String policyNumber,
		        Date policyReceiveDate, String policyReceiveBy, String flagInsActivation, String flagReNew, String flagInsStatus, Date sppadate, String sppano, String insuranceRateType, double mainStdPremium, double srccstdPremium,
		        double floodStdPremium, double tplstdPremium, double tplstdAmount, double totalStdPremium, double sumInsured, double srcctoInsco, double tpltoInsco, double floodToInsCo, double loadingFeeToInsCo, double mainPremiumToInsCo,
		        double premiumAmountToInsCo, Date insCoSelectionDate, double sellingRate, double sellingAmount, double adminFee, double meteraiFee, double paidAmountToInsco, double earnAmount, String insNotes, String accNotes, Date requestDate,
		        Date insActivateDate, short insLength, String mainCoverage, String additionalCoverage, String endorsDocNo, String bdendorsDocNo, Date bdendorsDate, String bdendorsPolicyNo, Date bdendorsPolicyReceiveDate, double endorsToInsCoPremium,
		        double endorsPaidToInsCo, double endorsAdditionalPremium, String flagClaimProcess, Date lastClaimDate, char flagDocStatus, double paidAmountByCust, Double waivedAmountByCust, Date paidDate, double lateCharges, long accPayId,
		        String insuredBy, String insurancePaidBy, double claimAmount, double paidClaimAmount, int yearNum, Date terminationDate, String isChangeInsCo, String changeInsCoReason, String coverPeriod, String renewalDocNo, Date renewalDocDate,
		        Double premiumBaseForRefundSupp, String invoiceNo, Double invoiceAmount, Date invoiceDate, Date receivedInvoiceDate, Date flagInsStatusDate, Character sppaprintStatus, boolean isValidCustomerName, boolean isValidAddress,
		        boolean isValidInsurancePeriode, boolean isValidInsLength, boolean isValidNumOfAsset, boolean isValid, Double insCapitalizedAmount, Double addCapitalizedAmount, short isNewCover, String batchId, Date batchDate, String generate,
		        String typeCorrectionCode, Date confirmDate, String usrCrt, Date dtmUpd, String usrUpd, Date dtmCrt)
			{
				this.id = id;
				this.agrmnt = agrmnt;
				this.appId = appId;
				this.currencyId = currencyId;
				this.insuranceCoyId = insuranceCoyId;
				this.insuranceCoyBranchId = insuranceCoyBranchId;
				this.applicationType = applicationType;
				this.mainPremiumToCust = mainPremiumToCust;
				this.loadingFeeToCust = loadingFeeToCust;
				this.tpltoCust = tpltoCust;
				this.floodToCust = floodToCust;
				this.srcctoCust = srcctoCust;
				this.premiumAmountByCustBeforeDisc = premiumAmountByCustBeforeDisc;
				this.discToCustAmount = discToCustAmount;
				this.premiumAmountByCust = premiumAmountByCust;
				this.adminFeeToCust = adminFeeToCust;
				this.meteraiFeeToCust = meteraiFeeToCust;
				this.capitalizedAmount = capitalizedAmount;
				this.startDate = startDate;
				this.endDate = endDate;
				this.policyNumber = policyNumber;
				this.policyReceiveDate = policyReceiveDate;
				this.policyReceiveBy = policyReceiveBy;
				this.flagInsActivation = flagInsActivation;
				this.flagReNew = flagReNew;
				this.flagInsStatus = flagInsStatus;
				this.sppadate = sppadate;
				this.sppano = sppano;
				this.insuranceRateType = insuranceRateType;
				this.mainStdPremium = mainStdPremium;
				this.srccstdPremium = srccstdPremium;
				this.floodStdPremium = floodStdPremium;
				this.tplstdPremium = tplstdPremium;
				this.tplstdAmount = tplstdAmount;
				this.totalStdPremium = totalStdPremium;
				this.sumInsured = sumInsured;
				this.srcctoInsco = srcctoInsco;
				this.tpltoInsco = tpltoInsco;
				this.floodToInsCo = floodToInsCo;
				this.loadingFeeToInsCo = loadingFeeToInsCo;
				this.mainPremiumToInsCo = mainPremiumToInsCo;
				this.premiumAmountToInsCo = premiumAmountToInsCo;
				this.insCoSelectionDate = insCoSelectionDate;
				this.sellingRate = sellingRate;
				this.sellingAmount = sellingAmount;
				this.adminFee = adminFee;
				this.meteraiFee = meteraiFee;
				this.paidAmountToInsco = paidAmountToInsco;
				this.earnAmount = earnAmount;
				this.insNotes = insNotes;
				this.accNotes = accNotes;
				this.requestDate = requestDate;
				this.insActivateDate = insActivateDate;
				this.insLength = insLength;
				this.mainCoverage = mainCoverage;
				this.additionalCoverage = additionalCoverage;
				this.endorsDocNo = endorsDocNo;
				this.bdendorsDocNo = bdendorsDocNo;
				this.bdendorsDate = bdendorsDate;
				this.bdendorsPolicyNo = bdendorsPolicyNo;
				this.bdendorsPolicyReceiveDate = bdendorsPolicyReceiveDate;
				this.endorsToInsCoPremium = endorsToInsCoPremium;
				this.endorsPaidToInsCo = endorsPaidToInsCo;
				this.endorsAdditionalPremium = endorsAdditionalPremium;
				this.flagClaimProcess = flagClaimProcess;
				this.lastClaimDate = lastClaimDate;
				this.flagDocStatus = flagDocStatus;
				this.paidAmountByCust = paidAmountByCust;
				this.waivedAmountByCust = waivedAmountByCust;
				this.paidDate = paidDate;
				this.lateCharges = lateCharges;
				this.accPayId = accPayId;
				this.insuredBy = insuredBy;
				this.insurancePaidBy = insurancePaidBy;
				this.claimAmount = claimAmount;
				this.paidClaimAmount = paidClaimAmount;
				this.yearNum = yearNum;
				this.terminationDate = terminationDate;
				this.isChangeInsCo = isChangeInsCo;
				this.changeInsCoReason = changeInsCoReason;
				this.coverPeriod = coverPeriod;
				this.renewalDocNo = renewalDocNo;
				this.renewalDocDate = renewalDocDate;
				this.premiumBaseForRefundSupp = premiumBaseForRefundSupp;
				this.invoiceNo = invoiceNo;
				this.invoiceAmount = invoiceAmount;
				this.invoiceDate = invoiceDate;
				this.receivedInvoiceDate = receivedInvoiceDate;
				this.flagInsStatusDate = flagInsStatusDate;
				this.sppaprintStatus = sppaprintStatus;
				this.isValidCustomerName = isValidCustomerName;
				this.isValidAddress = isValidAddress;
				this.isValidInsurancePeriode = isValidInsurancePeriode;
				this.isValidInsLength = isValidInsLength;
				this.isValidNumOfAsset = isValidNumOfAsset;
				this.isValid = isValid;
				this.insCapitalizedAmount = insCapitalizedAmount;
				this.addCapitalizedAmount = addCapitalizedAmount;
				this.isNewCover = isNewCover;
				this.batchId = batchId;
				this.batchDate = batchDate;
				this.generate = generate;
				this.typeCorrectionCode = typeCorrectionCode;
				this.confirmDate = confirmDate;
				this.usrCrt = usrCrt;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
			}
			
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "AgrmntId")
		public Agrmnt getAgrmnt()
			{
				return this.agrmnt;
			}
			
		public void setAgrmnt(Agrmnt agrmnt)
			{
				this.agrmnt = agrmnt;
			}
			
		@Column(name = "AppId")
		public Long getAppId()
			{
				return this.appId;
			}
			
		public void setAppId(Long appId)
			{
				this.appId = appId;
			}
			
		@Column(name = "CurrencyId")
		public Long getCurrencyId()
			{
				return this.currencyId;
			}
			
		public void setCurrencyId(Long currencyId)
			{
				this.currencyId = currencyId;
			}
			
		@Column(name = "InsuranceCoyId")
		public Long getInsuranceCoyId()
			{
				return this.insuranceCoyId;
			}
			
		public void setInsuranceCoyId(Long insuranceCoyId)
			{
				this.insuranceCoyId = insuranceCoyId;
			}
			
		@Column(name = "InsuranceCoyBranchID")
		public Long getInsuranceCoyBranchId()
			{
				return this.insuranceCoyBranchId;
			}
			
		public void setInsuranceCoyBranchId(Long insuranceCoyBranchId)
			{
				this.insuranceCoyBranchId = insuranceCoyBranchId;
			}
			
		@Column(name = "ApplicationType", length = 10)
		public String getApplicationType()
			{
				return this.applicationType;
			}
			
		public void setApplicationType(String applicationType)
			{
				this.applicationType = applicationType;
			}
			
		@Column(name = "MainPremiumToCust", nullable = false, precision = 53, scale = 0)
		public double getMainPremiumToCust()
			{
				return this.mainPremiumToCust;
			}
			
		public void setMainPremiumToCust(double mainPremiumToCust)
			{
				this.mainPremiumToCust = mainPremiumToCust;
			}
			
		@Column(name = "LoadingFeeToCust", nullable = false, precision = 53, scale = 0)
		public double getLoadingFeeToCust()
			{
				return this.loadingFeeToCust;
			}
			
		public void setLoadingFeeToCust(double loadingFeeToCust)
			{
				this.loadingFeeToCust = loadingFeeToCust;
			}
			
		@Column(name = "TPLToCust", nullable = false, precision = 53, scale = 0)
		public double getTpltoCust()
			{
				return this.tpltoCust;
			}
			
		public void setTpltoCust(double tpltoCust)
			{
				this.tpltoCust = tpltoCust;
			}
			
		@Column(name = "FloodToCust", nullable = false, precision = 53, scale = 0)
		public double getFloodToCust()
			{
				return this.floodToCust;
			}
			
		public void setFloodToCust(double floodToCust)
			{
				this.floodToCust = floodToCust;
			}
			
		@Column(name = "SRCCToCust", nullable = false, precision = 53, scale = 0)
		public double getSrcctoCust()
			{
				return this.srcctoCust;
			}
			
		public void setSrcctoCust(double srcctoCust)
			{
				this.srcctoCust = srcctoCust;
			}
			
		@Column(name = "PremiumAmountByCustBeforeDisc", nullable = false, precision = 53, scale = 0)
		public double getPremiumAmountByCustBeforeDisc()
			{
				return this.premiumAmountByCustBeforeDisc;
			}
			
		public void setPremiumAmountByCustBeforeDisc(double premiumAmountByCustBeforeDisc)
			{
				this.premiumAmountByCustBeforeDisc = premiumAmountByCustBeforeDisc;
			}
			
		@Column(name = "DiscToCustAmount", nullable = false, precision = 53, scale = 0)
		public double getDiscToCustAmount()
			{
				return this.discToCustAmount;
			}
			
		public void setDiscToCustAmount(double discToCustAmount)
			{
				this.discToCustAmount = discToCustAmount;
			}
			
		@Column(name = "PremiumAmountByCust", nullable = false, precision = 53, scale = 0)
		public double getPremiumAmountByCust()
			{
				return this.premiumAmountByCust;
			}
			
		public void setPremiumAmountByCust(double premiumAmountByCust)
			{
				this.premiumAmountByCust = premiumAmountByCust;
			}
			
		@Column(name = "AdminFeeToCust", nullable = false, precision = 53, scale = 0)
		public double getAdminFeeToCust()
			{
				return this.adminFeeToCust;
			}
			
		public void setAdminFeeToCust(double adminFeeToCust)
			{
				this.adminFeeToCust = adminFeeToCust;
			}
			
		@Column(name = "MeteraiFeeToCust", nullable = false, precision = 53, scale = 0)
		public double getMeteraiFeeToCust()
			{
				return this.meteraiFeeToCust;
			}
			
		public void setMeteraiFeeToCust(double meteraiFeeToCust)
			{
				this.meteraiFeeToCust = meteraiFeeToCust;
			}
			
		@Column(name = "CapitalizedAmount", nullable = false, precision = 53, scale = 0)
		public double getCapitalizedAmount()
			{
				return this.capitalizedAmount;
			}
			
		public void setCapitalizedAmount(double capitalizedAmount)
			{
				this.capitalizedAmount = capitalizedAmount;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "StartDate", length = 23)
		public Date getStartDate()
			{
				return this.startDate;
			}
			
		public void setStartDate(Date startDate)
			{
				this.startDate = startDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "EndDate", length = 23)
		public Date getEndDate()
			{
				return this.endDate;
			}
			
		public void setEndDate(Date endDate)
			{
				this.endDate = endDate;
			}
			
		@Column(name = "PolicyNumber", nullable = false, length = 25)
		public String getPolicyNumber()
			{
				return this.policyNumber;
			}
			
		public void setPolicyNumber(String policyNumber)
			{
				this.policyNumber = policyNumber;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "PolicyReceiveDate", length = 23)
		public Date getPolicyReceiveDate()
			{
				return this.policyReceiveDate;
			}
			
		public void setPolicyReceiveDate(Date policyReceiveDate)
			{
				this.policyReceiveDate = policyReceiveDate;
			}
			
		@Column(name = "PolicyReceiveBy", nullable = false, length = 12)
		public String getPolicyReceiveBy()
			{
				return this.policyReceiveBy;
			}
			
		public void setPolicyReceiveBy(String policyReceiveBy)
			{
				this.policyReceiveBy = policyReceiveBy;
			}
			
		@Column(name = "FlagInsActivation", length = 1)
		public String getFlagInsActivation()
			{
				return this.flagInsActivation;
			}
			
		public void setFlagInsActivation(String flagInsActivation)
			{
				this.flagInsActivation = flagInsActivation;
			}
			
		@Column(name = "FlagReNew", nullable = false, length = 1)
		public String getFlagReNew()
			{
				return this.flagReNew;
			}
			
		public void setFlagReNew(String flagReNew)
			{
				this.flagReNew = flagReNew;
			}
			
		@Column(name = "FlagInsStatus", nullable = false, length = 1)
		public String getFlagInsStatus()
			{
				return this.flagInsStatus;
			}
			
		public void setFlagInsStatus(String flagInsStatus)
			{
				this.flagInsStatus = flagInsStatus;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "SPPADate", length = 23)
		public Date getSppadate()
			{
				return this.sppadate;
			}
			
		public void setSppadate(Date sppadate)
			{
				this.sppadate = sppadate;
			}
			
		@Column(name = "SPPANo", nullable = false, length = 30)
		public String getSppano()
			{
				return this.sppano;
			}
			
		public void setSppano(String sppano)
			{
				this.sppano = sppano;
			}
			
		@Column(name = "InsuranceRateType", nullable = false, length = 20)
		public String getInsuranceRateType()
			{
				return this.insuranceRateType;
			}
			
		public void setInsuranceRateType(String insuranceRateType)
			{
				this.insuranceRateType = insuranceRateType;
			}
			
		@Column(name = "MainStdPremium", nullable = false, precision = 53, scale = 0)
		public double getMainStdPremium()
			{
				return this.mainStdPremium;
			}
			
		public void setMainStdPremium(double mainStdPremium)
			{
				this.mainStdPremium = mainStdPremium;
			}
			
		@Column(name = "SRCCStdPremium", nullable = false, precision = 53, scale = 0)
		public double getSrccstdPremium()
			{
				return this.srccstdPremium;
			}
			
		public void setSrccstdPremium(double srccstdPremium)
			{
				this.srccstdPremium = srccstdPremium;
			}
			
		@Column(name = "FloodStdPremium", nullable = false, precision = 53, scale = 0)
		public double getFloodStdPremium()
			{
				return this.floodStdPremium;
			}
			
		public void setFloodStdPremium(double floodStdPremium)
			{
				this.floodStdPremium = floodStdPremium;
			}
			
		@Column(name = "TPLStdPremium", nullable = false, precision = 53, scale = 0)
		public double getTplstdPremium()
			{
				return this.tplstdPremium;
			}
			
		public void setTplstdPremium(double tplstdPremium)
			{
				this.tplstdPremium = tplstdPremium;
			}
			
		@Column(name = "TPLStdAmount", nullable = false, precision = 53, scale = 0)
		public double getTplstdAmount()
			{
				return this.tplstdAmount;
			}
			
		public void setTplstdAmount(double tplstdAmount)
			{
				this.tplstdAmount = tplstdAmount;
			}
			
		@Column(name = "TotalStdPremium", nullable = false, precision = 53, scale = 0)
		public double getTotalStdPremium()
			{
				return this.totalStdPremium;
			}
			
		public void setTotalStdPremium(double totalStdPremium)
			{
				this.totalStdPremium = totalStdPremium;
			}
			
		@Column(name = "SumInsured", nullable = false, precision = 53, scale = 0)
		public double getSumInsured()
			{
				return this.sumInsured;
			}
			
		public void setSumInsured(double sumInsured)
			{
				this.sumInsured = sumInsured;
			}
			
		@Column(name = "SRCCToInsco", nullable = false, precision = 53, scale = 0)
		public double getSrcctoInsco()
			{
				return this.srcctoInsco;
			}
			
		public void setSrcctoInsco(double srcctoInsco)
			{
				this.srcctoInsco = srcctoInsco;
			}
			
		@Column(name = "TPLToInsco", nullable = false, precision = 53, scale = 0)
		public double getTpltoInsco()
			{
				return this.tpltoInsco;
			}
			
		public void setTpltoInsco(double tpltoInsco)
			{
				this.tpltoInsco = tpltoInsco;
			}
			
		@Column(name = "FloodToInsCo", nullable = false, precision = 53, scale = 0)
		public double getFloodToInsCo()
			{
				return this.floodToInsCo;
			}
			
		public void setFloodToInsCo(double floodToInsCo)
			{
				this.floodToInsCo = floodToInsCo;
			}
			
		@Column(name = "LoadingFeeToInsCo", nullable = false, precision = 53, scale = 0)
		public double getLoadingFeeToInsCo()
			{
				return this.loadingFeeToInsCo;
			}
			
		public void setLoadingFeeToInsCo(double loadingFeeToInsCo)
			{
				this.loadingFeeToInsCo = loadingFeeToInsCo;
			}
			
		@Column(name = "MainPremiumToInsCo", nullable = false, precision = 53, scale = 0)
		public double getMainPremiumToInsCo()
			{
				return this.mainPremiumToInsCo;
			}
			
		public void setMainPremiumToInsCo(double mainPremiumToInsCo)
			{
				this.mainPremiumToInsCo = mainPremiumToInsCo;
			}
			
		@Column(name = "PremiumAmountToInsCo", nullable = false, precision = 53, scale = 0)
		public double getPremiumAmountToInsCo()
			{
				return this.premiumAmountToInsCo;
			}
			
		public void setPremiumAmountToInsCo(double premiumAmountToInsCo)
			{
				this.premiumAmountToInsCo = premiumAmountToInsCo;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "InsCoSelectionDate", length = 23)
		public Date getInsCoSelectionDate()
			{
				return this.insCoSelectionDate;
			}
			
		public void setInsCoSelectionDate(Date insCoSelectionDate)
			{
				this.insCoSelectionDate = insCoSelectionDate;
			}
			
		@Column(name = "SellingRate", nullable = false, precision = 53, scale = 0)
		public double getSellingRate()
			{
				return this.sellingRate;
			}
			
		public void setSellingRate(double sellingRate)
			{
				this.sellingRate = sellingRate;
			}
			
		@Column(name = "SellingAmount", nullable = false, precision = 53, scale = 0)
		public double getSellingAmount()
			{
				return this.sellingAmount;
			}
			
		public void setSellingAmount(double sellingAmount)
			{
				this.sellingAmount = sellingAmount;
			}
			
		@Column(name = "AdminFee", nullable = false, precision = 53, scale = 0)
		public double getAdminFee()
			{
				return this.adminFee;
			}
			
		public void setAdminFee(double adminFee)
			{
				this.adminFee = adminFee;
			}
			
		@Column(name = "MeteraiFee", nullable = false, precision = 53, scale = 0)
		public double getMeteraiFee()
			{
				return this.meteraiFee;
			}
			
		public void setMeteraiFee(double meteraiFee)
			{
				this.meteraiFee = meteraiFee;
			}
			
		@Column(name = "PaidAmountToInsco", nullable = false, precision = 53, scale = 0)
		public double getPaidAmountToInsco()
			{
				return this.paidAmountToInsco;
			}
			
		public void setPaidAmountToInsco(double paidAmountToInsco)
			{
				this.paidAmountToInsco = paidAmountToInsco;
			}
			
		@Column(name = "EarnAmount", nullable = false, precision = 53, scale = 0)
		public double getEarnAmount()
			{
				return this.earnAmount;
			}
			
		public void setEarnAmount(double earnAmount)
			{
				this.earnAmount = earnAmount;
			}
			
		@Column(name = "InsNotes", nullable = false, length = 500)
		public String getInsNotes()
			{
				return this.insNotes;
			}
			
		public void setInsNotes(String insNotes)
			{
				this.insNotes = insNotes;
			}
			
		@Column(name = "AccNotes", nullable = false, length = 500)
		public String getAccNotes()
			{
				return this.accNotes;
			}
			
		public void setAccNotes(String accNotes)
			{
				this.accNotes = accNotes;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "RequestDate", length = 23)
		public Date getRequestDate()
			{
				return this.requestDate;
			}
			
		public void setRequestDate(Date requestDate)
			{
				this.requestDate = requestDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "InsActivateDate", length = 23)
		public Date getInsActivateDate()
			{
				return this.insActivateDate;
			}
			
		public void setInsActivateDate(Date insActivateDate)
			{
				this.insActivateDate = insActivateDate;
			}
			
		@Column(name = "InsLength", nullable = false)
		public short getInsLength()
			{
				return this.insLength;
			}
			
		public void setInsLength(short insLength)
			{
				this.insLength = insLength;
			}
			
		@Column(name = "MainCoverage", nullable = false, length = 50)
		public String getMainCoverage()
			{
				return this.mainCoverage;
			}
			
		public void setMainCoverage(String mainCoverage)
			{
				this.mainCoverage = mainCoverage;
			}
			
		@Column(name = "AdditionalCoverage", nullable = false, length = 50)
		public String getAdditionalCoverage()
			{
				return this.additionalCoverage;
			}
			
		public void setAdditionalCoverage(String additionalCoverage)
			{
				this.additionalCoverage = additionalCoverage;
			}
			
		@Column(name = "EndorsDocNo", nullable = false, length = 20)
		public String getEndorsDocNo()
			{
				return this.endorsDocNo;
			}
			
		public void setEndorsDocNo(String endorsDocNo)
			{
				this.endorsDocNo = endorsDocNo;
			}
			
		@Column(name = "BDEndorsDocNo", nullable = false, length = 20)
		public String getBdendorsDocNo()
			{
				return this.bdendorsDocNo;
			}
			
		public void setBdendorsDocNo(String bdendorsDocNo)
			{
				this.bdendorsDocNo = bdendorsDocNo;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "BDEndorsDate", length = 23)
		public Date getBdendorsDate()
			{
				return this.bdendorsDate;
			}
			
		public void setBdendorsDate(Date bdendorsDate)
			{
				this.bdendorsDate = bdendorsDate;
			}
			
		@Column(name = "BDEndorsPolicyNo", nullable = false, length = 25)
		public String getBdendorsPolicyNo()
			{
				return this.bdendorsPolicyNo;
			}
			
		public void setBdendorsPolicyNo(String bdendorsPolicyNo)
			{
				this.bdendorsPolicyNo = bdendorsPolicyNo;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "BDEndorsPolicyReceiveDate", length = 23)
		public Date getBdendorsPolicyReceiveDate()
			{
				return this.bdendorsPolicyReceiveDate;
			}
			
		public void setBdendorsPolicyReceiveDate(Date bdendorsPolicyReceiveDate)
			{
				this.bdendorsPolicyReceiveDate = bdendorsPolicyReceiveDate;
			}
			
		@Column(name = "EndorsToInsCoPremium", nullable = false, precision = 53, scale = 0)
		public double getEndorsToInsCoPremium()
			{
				return this.endorsToInsCoPremium;
			}
			
		public void setEndorsToInsCoPremium(double endorsToInsCoPremium)
			{
				this.endorsToInsCoPremium = endorsToInsCoPremium;
			}
			
		@Column(name = "EndorsPaidToInsCo", nullable = false, precision = 53, scale = 0)
		public double getEndorsPaidToInsCo()
			{
				return this.endorsPaidToInsCo;
			}
			
		public void setEndorsPaidToInsCo(double endorsPaidToInsCo)
			{
				this.endorsPaidToInsCo = endorsPaidToInsCo;
			}
			
		@Column(name = "EndorsAdditionalPremium", nullable = false, precision = 53, scale = 0)
		public double getEndorsAdditionalPremium()
			{
				return this.endorsAdditionalPremium;
			}
			
		public void setEndorsAdditionalPremium(double endorsAdditionalPremium)
			{
				this.endorsAdditionalPremium = endorsAdditionalPremium;
			}
			
		@Column(name = "FlagClaimProcess", nullable = false, length = 1)
		public String getFlagClaimProcess()
			{
				return this.flagClaimProcess;
			}
			
		public void setFlagClaimProcess(String flagClaimProcess)
			{
				this.flagClaimProcess = flagClaimProcess;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastClaimDate", length = 23)
		public Date getLastClaimDate()
			{
				return this.lastClaimDate;
			}
			
		public void setLastClaimDate(Date lastClaimDate)
			{
				this.lastClaimDate = lastClaimDate;
			}
			
		@Column(name = "FlagDocStatus", nullable = false, length = 1)
		public char getFlagDocStatus()
			{
				return this.flagDocStatus;
			}
			
		public void setFlagDocStatus(char flagDocStatus)
			{
				this.flagDocStatus = flagDocStatus;
			}
			
		@Column(name = "PaidAmountByCust", nullable = false, precision = 53, scale = 0)
		public double getPaidAmountByCust()
			{
				return this.paidAmountByCust;
			}
			
		public void setPaidAmountByCust(double paidAmountByCust)
			{
				this.paidAmountByCust = paidAmountByCust;
			}
			
		@Column(name = "WaivedAmountByCust", precision = 53, scale = 0)
		public Double getWaivedAmountByCust()
			{
				return this.waivedAmountByCust;
			}
			
		public void setWaivedAmountByCust(Double waivedAmountByCust)
			{
				this.waivedAmountByCust = waivedAmountByCust;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "PaidDate", length = 23)
		public Date getPaidDate()
			{
				return this.paidDate;
			}
			
		public void setPaidDate(Date paidDate)
			{
				this.paidDate = paidDate;
			}
			
		@Column(name = "LateCharges", nullable = false, precision = 53, scale = 0)
		public double getLateCharges()
			{
				return this.lateCharges;
			}
			
		public void setLateCharges(double lateCharges)
			{
				this.lateCharges = lateCharges;
			}
			
		@Column(name = "AccPayId", nullable = false)
		public long getAccPayId()
			{
				return this.accPayId;
			}
			
		public void setAccPayId(long accPayId)
			{
				this.accPayId = accPayId;
			}
			
		@Column(name = "InsuredBy", length = 10)
		public String getInsuredBy()
			{
				return this.insuredBy;
			}
			
		public void setInsuredBy(String insuredBy)
			{
				this.insuredBy = insuredBy;
			}
			
		@Column(name = "InsurancePaidBy", length = 10)
		public String getInsurancePaidBy()
			{
				return this.insurancePaidBy;
			}
			
		public void setInsurancePaidBy(String insurancePaidBy)
			{
				this.insurancePaidBy = insurancePaidBy;
			}
			
		@Column(name = "ClaimAmount", nullable = false, precision = 53, scale = 0)
		public double getClaimAmount()
			{
				return this.claimAmount;
			}
			
		public void setClaimAmount(double claimAmount)
			{
				this.claimAmount = claimAmount;
			}
			
		@Column(name = "PaidClaimAmount", nullable = false, precision = 53, scale = 0)
		public double getPaidClaimAmount()
			{
				return this.paidClaimAmount;
			}
			
		public void setPaidClaimAmount(double paidClaimAmount)
			{
				this.paidClaimAmount = paidClaimAmount;
			}
			
		@Column(name = "YearNum", nullable = false)
		public int getYearNum()
			{
				return this.yearNum;
			}
			
		public void setYearNum(int yearNum)
			{
				this.yearNum = yearNum;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "TerminationDate", length = 23)
		public Date getTerminationDate()
			{
				return this.terminationDate;
			}
			
		public void setTerminationDate(Date terminationDate)
			{
				this.terminationDate = terminationDate;
			}
			
		@Column(name = "IsChangeInsCo", nullable = false, length = 1)
		public String getIsChangeInsCo()
			{
				return this.isChangeInsCo;
			}
			
		public void setIsChangeInsCo(String isChangeInsCo)
			{
				this.isChangeInsCo = isChangeInsCo;
			}
			
		@Column(name = "ChangeInsCoReason", nullable = false, length = 50)
		public String getChangeInsCoReason()
			{
				return this.changeInsCoReason;
			}
			
		public void setChangeInsCoReason(String changeInsCoReason)
			{
				this.changeInsCoReason = changeInsCoReason;
			}
			
		@Column(name = "CoverPeriod", nullable = false, length = 2)
		public String getCoverPeriod()
			{
				return this.coverPeriod;
			}
			
		public void setCoverPeriod(String coverPeriod)
			{
				this.coverPeriod = coverPeriod;
			}
			
		@Column(name = "RenewalDocNo", nullable = false, length = 20)
		public String getRenewalDocNo()
			{
				return this.renewalDocNo;
			}
			
		public void setRenewalDocNo(String renewalDocNo)
			{
				this.renewalDocNo = renewalDocNo;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "RenewalDocDate", length = 23)
		public Date getRenewalDocDate()
			{
				return this.renewalDocDate;
			}
			
		public void setRenewalDocDate(Date renewalDocDate)
			{
				this.renewalDocDate = renewalDocDate;
			}
			
		@Column(name = "PremiumBaseForRefundSupp", nullable = false, precision = 17)
		public Double getPremiumBaseForRefundSupp()
			{
				return this.premiumBaseForRefundSupp;
			}
			
		public void setPremiumBaseForRefundSupp(Double premiumBaseForRefundSupp)
			{
				this.premiumBaseForRefundSupp = premiumBaseForRefundSupp;
			}
			
		@Column(name = "InvoiceNo", length = 20)
		public String getInvoiceNo()
			{
				return this.invoiceNo;
			}
			
		public void setInvoiceNo(String invoiceNo)
			{
				this.invoiceNo = invoiceNo;
			}
			
		@Column(name = "InvoiceAmount", precision = 17)
		public Double getInvoiceAmount()
			{
				return this.invoiceAmount;
			}
			
		public void setInvoiceAmount(Double invoiceAmount)
			{
				this.invoiceAmount = invoiceAmount;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "InvoiceDate", length = 23)
		public Date getInvoiceDate()
			{
				return this.invoiceDate;
			}
			
		public void setInvoiceDate(Date invoiceDate)
			{
				this.invoiceDate = invoiceDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "ReceivedInvoiceDate", length = 23)
		public Date getReceivedInvoiceDate()
			{
				return this.receivedInvoiceDate;
			}
			
		public void setReceivedInvoiceDate(Date receivedInvoiceDate)
			{
				this.receivedInvoiceDate = receivedInvoiceDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "FlagInsStatusDate", length = 23)
		public Date getFlagInsStatusDate()
			{
				return this.flagInsStatusDate;
			}
			
		public void setFlagInsStatusDate(Date flagInsStatusDate)
			{
				this.flagInsStatusDate = flagInsStatusDate;
			}
			
		@Column(name = "SPPAPrintStatus", length = 1)
		public Character getSppaprintStatus()
			{
				return this.sppaprintStatus;
			}
			
		public void setSppaprintStatus(Character sppaprintStatus)
			{
				this.sppaprintStatus = sppaprintStatus;
			}
			
		@Column(name = "IsValidCustomerName", nullable = false)
		public boolean isIsValidCustomerName()
			{
				return this.isValidCustomerName;
			}
			
		public void setIsValidCustomerName(boolean isValidCustomerName)
			{
				this.isValidCustomerName = isValidCustomerName;
			}
			
		@Column(name = "IsValidAddress", nullable = false)
		public boolean isIsValidAddress()
			{
				return this.isValidAddress;
			}
			
		public void setIsValidAddress(boolean isValidAddress)
			{
				this.isValidAddress = isValidAddress;
			}
			
		@Column(name = "IsValidInsurancePeriode", nullable = false)
		public boolean isIsValidInsurancePeriode()
			{
				return this.isValidInsurancePeriode;
			}
			
		public void setIsValidInsurancePeriode(boolean isValidInsurancePeriode)
			{
				this.isValidInsurancePeriode = isValidInsurancePeriode;
			}
			
		@Column(name = "IsValidInsLength", nullable = false)
		public boolean isIsValidInsLength()
			{
				return this.isValidInsLength;
			}
			
		public void setIsValidInsLength(boolean isValidInsLength)
			{
				this.isValidInsLength = isValidInsLength;
			}
			
		@Column(name = "IsValidNumOfAsset", nullable = false)
		public boolean isIsValidNumOfAsset()
			{
				return this.isValidNumOfAsset;
			}
			
		public void setIsValidNumOfAsset(boolean isValidNumOfAsset)
			{
				this.isValidNumOfAsset = isValidNumOfAsset;
			}
			
		@Column(name = "IsValid", nullable = false)
		public boolean isIsValid()
			{
				return this.isValid;
			}
			
		public void setIsValid(boolean isValid)
			{
				this.isValid = isValid;
			}
			
		@Column(name = "InsCapitalizedAmount", precision = 17)
		public Double getInsCapitalizedAmount()
			{
				return this.insCapitalizedAmount;
			}
			
		public void setInsCapitalizedAmount(Double insCapitalizedAmount)
			{
				this.insCapitalizedAmount = insCapitalizedAmount;
			}
			
		@Column(name = "AddCapitalizedAmount", precision = 17)
		public Double getAddCapitalizedAmount()
			{
				return this.addCapitalizedAmount;
			}
			
		public void setAddCapitalizedAmount(Double addCapitalizedAmount)
			{
				this.addCapitalizedAmount = addCapitalizedAmount;
			}
			
		@Column(name = "IsNewCover", nullable = false)
		public short getIsNewCover()
			{
				return this.isNewCover;
			}
			
		public void setIsNewCover(short isNewCover)
			{
				this.isNewCover = isNewCover;
			}
			
		@Column(name = "BatchID", length = 20)
		public String getBatchId()
			{
				return this.batchId;
			}
			
		public void setBatchId(String batchId)
			{
				this.batchId = batchId;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "BatchDate", length = 23)
		public Date getBatchDate()
			{
				return this.batchDate;
			}
			
		public void setBatchDate(Date batchDate)
			{
				this.batchDate = batchDate;
			}
			
		@Column(name = "Generate", length = 4)
		public String getGenerate()
			{
				return this.generate;
			}
			
		public void setGenerate(String generate)
			{
				this.generate = generate;
			}
			
		@Column(name = "TypeCorrectionCode", length = 10)
		public String getTypeCorrectionCode()
			{
				return this.typeCorrectionCode;
			}
			
		public void setTypeCorrectionCode(String typeCorrectionCode)
			{
				this.typeCorrectionCode = typeCorrectionCode;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "ConfirmDate", length = 23)
		public Date getConfirmDate()
			{
				return this.confirmDate;
			}
			
		public void setConfirmDate(Date confirmDate)
			{
				this.confirmDate = confirmDate;
			}
			
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
	}
