
package com.adibrata.smartdealer.model;
// Generated Aug 21, 2015 4:05:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agrmnt generated by hbm2java
 */
@Entity
@Table(name = "Agrmnt", catalog = "SmartDealer")
public class Agrmnt implements java.io.Serializable
	{
		
		private long id;
		private Application application;
		private Currency currency;
		private Customer customerBySpouseId;
		private Customer customerByGuarantorId;
		private Customer customerByCustomerId;
		private Marketing marketing;
		private Office office;
		private Partner partner;
		private String agrmntCode;
		private String coaSchmCode;
		private Long prodId;
		private Long potId;
		private Short numOfAsset;
		private String interestTypeCode;
		private String instSchemeCode;
		private String guarantorRelation;
		private String wopCode;
		private String sourceAppCode;
		private Date agreementDate;
		private String notes;
		private Double osP;
		private Double osI;
		private Double osPundue;
		private Double osIundue;
		private Double instAmount;
		private Short nextInstNumber;
		private Date nextInstDate;
		private Short nextInstDueNumber;
		private Date nextInstDueDate;
		private Double prepaidAmt;
		private Short tenor;
		private Short cummulativeTenor;
		private Date effectiveDate;
		private Date goLiveDate;
		private Date rrddate;
		private String contractStatus;
		private String defaultStatus;
		private Double percentagePenalty;
		private String usrCrt;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private Set<PdcHdr> pdcHdrs = new HashSet<PdcHdr>(0);
		private Set<SuspendAllocation> suspendAllocations = new HashSet<SuspendAllocation>(0);
		private Set<AgrmntMnt> agrmntMnts = new HashSet<AgrmntMnt>(0);
		private Set<AgrmntFund> agrmntFunds = new HashSet<AgrmntFund>(0);
		private Set<InstSchedule> instSchedules = new HashSet<InstSchedule>(0);
		private Set<AgrmntBankStatementInfo> agrmntBankStatementInfos = new HashSet<AgrmntBankStatementInfo>(0);
		private Set<AgrmntReffInfo> agrmntReffInfos = new HashSet<AgrmntReffInfo>(0);
		private Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId = new HashSet<AgrmntCrossDefault>(0);
		private Set<PaymentReversal> paymentReversals = new HashSet<PaymentReversal>(0);
		private Set<AgrmntCrossDefault> agrmntCrossDefaultsForCrossAgrmntId = new HashSet<AgrmntCrossDefault>(0);
		private Set<DeliveryOrder> deliveryOrders = new HashSet<DeliveryOrder>(0);
		private Set<EarlyTermination> earlyTerminations = new HashSet<EarlyTermination>(0);
		private Set<AgrmntGoLive> agrmntGoLives = new HashSet<AgrmntGoLive>(0);
		private Set<DailyAraging> dailyAragings = new HashSet<DailyAraging>(0);
		private Set<AgrmntTc> agrmntTcs = new HashSet<AgrmntTc>(0);
		private Set<AgrmntMailingInfo> agrmntMailingInfos = new HashSet<AgrmntMailingInfo>(0);
		private Set<AgrmntSuppEmplInfo> agrmntSuppEmplInfos = new HashSet<AgrmntSuppEmplInfo>(0);
		private Set<AgrmntColl> agrmntColls = new HashSet<AgrmntColl>(0);
		private Set<AgrmntAsset> agrmntAssets = new HashSet<AgrmntAsset>(0);
		private Set<PayHistHdr> payHistHdrs = new HashSet<PayHistHdr>(0);
		private Set<PaymentReceive> paymentReceives = new HashSet<PaymentReceive>(0);
		private Set<AgrmntInvoice> agrmntInvoices = new HashSet<AgrmntInvoice>(0);
		private Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId_1 = new HashSet<AgrmntCrossDefault>(0);
		private Set<AgrmntIns> agrmntInses = new HashSet<AgrmntIns>(0);
		private Set<AgrmntEmployeeInfo> agrmntEmployeeInfos = new HashSet<AgrmntEmployeeInfo>(0);
		
		public Agrmnt()
			{
			}
			
		public Agrmnt(long id)
			{
				this.id = id;
			}
			
		public Agrmnt(long id, Application application, Currency currency, Customer customerBySpouseId, Customer customerByGuarantorId, Customer customerByCustomerId, Marketing marketing, Office office, Partner partner, String agrmntCode,
		        String coaSchmCode, Long prodId, Long potId, Short numOfAsset, String interestTypeCode, String instSchemeCode, String guarantorRelation, String wopCode, String sourceAppCode, Date agreementDate, String notes, Double osP, Double osI,
		        Double osPundue, Double osIundue, Double instAmount, Short nextInstNumber, Date nextInstDate, Short nextInstDueNumber, Date nextInstDueDate, Double prepaidAmt, Short tenor, Short cummulativeTenor, Date effectiveDate, Date goLiveDate,
		        Date rrddate, String contractStatus, String defaultStatus, Double percentagePenalty, String usrCrt, Date dtmUpd, String usrUpd, Date dtmCrt, Set<PdcHdr> pdcHdrs, Set<SuspendAllocation> suspendAllocations, Set<AgrmntMnt> agrmntMnts,
		        Set<AgrmntFund> agrmntFunds, Set<InstSchedule> instSchedules, Set<AgrmntBankStatementInfo> agrmntBankStatementInfos, Set<AgrmntReffInfo> agrmntReffInfos, Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId,
		        Set<PaymentReversal> paymentReversals, Set<AgrmntCrossDefault> agrmntCrossDefaultsForCrossAgrmntId, Set<DeliveryOrder> deliveryOrders, Set<EarlyTermination> earlyTerminations, Set<AgrmntGoLive> agrmntGoLives,
		        Set<DailyAraging> dailyAragings, Set<AgrmntTc> agrmntTcs, Set<AgrmntMailingInfo> agrmntMailingInfos, Set<AgrmntSuppEmplInfo> agrmntSuppEmplInfos, Set<AgrmntColl> agrmntColls, Set<AgrmntAsset> agrmntAssets, Set<PayHistHdr> payHistHdrs,
		        Set<PaymentReceive> paymentReceives, Set<AgrmntInvoice> agrmntInvoices, Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId_1, Set<AgrmntIns> agrmntInses, Set<AgrmntEmployeeInfo> agrmntEmployeeInfos)
			{
				this.id = id;
				this.application = application;
				this.currency = currency;
				this.customerBySpouseId = customerBySpouseId;
				this.customerByGuarantorId = customerByGuarantorId;
				this.customerByCustomerId = customerByCustomerId;
				this.marketing = marketing;
				this.office = office;
				this.partner = partner;
				this.agrmntCode = agrmntCode;
				this.coaSchmCode = coaSchmCode;
				this.prodId = prodId;
				this.potId = potId;
				this.numOfAsset = numOfAsset;
				this.interestTypeCode = interestTypeCode;
				this.instSchemeCode = instSchemeCode;
				this.guarantorRelation = guarantorRelation;
				this.wopCode = wopCode;
				this.sourceAppCode = sourceAppCode;
				this.agreementDate = agreementDate;
				this.notes = notes;
				this.osP = osP;
				this.osI = osI;
				this.osPundue = osPundue;
				this.osIundue = osIundue;
				this.instAmount = instAmount;
				this.nextInstNumber = nextInstNumber;
				this.nextInstDate = nextInstDate;
				this.nextInstDueNumber = nextInstDueNumber;
				this.nextInstDueDate = nextInstDueDate;
				this.prepaidAmt = prepaidAmt;
				this.tenor = tenor;
				this.cummulativeTenor = cummulativeTenor;
				this.effectiveDate = effectiveDate;
				this.goLiveDate = goLiveDate;
				this.rrddate = rrddate;
				this.contractStatus = contractStatus;
				this.defaultStatus = defaultStatus;
				this.percentagePenalty = percentagePenalty;
				this.usrCrt = usrCrt;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.pdcHdrs = pdcHdrs;
				this.suspendAllocations = suspendAllocations;
				this.agrmntMnts = agrmntMnts;
				this.agrmntFunds = agrmntFunds;
				this.instSchedules = instSchedules;
				this.agrmntBankStatementInfos = agrmntBankStatementInfos;
				this.agrmntReffInfos = agrmntReffInfos;
				this.agrmntCrossDefaultsForAgrmntId = agrmntCrossDefaultsForAgrmntId;
				this.paymentReversals = paymentReversals;
				this.agrmntCrossDefaultsForCrossAgrmntId = agrmntCrossDefaultsForCrossAgrmntId;
				this.deliveryOrders = deliveryOrders;
				this.earlyTerminations = earlyTerminations;
				this.agrmntGoLives = agrmntGoLives;
				this.dailyAragings = dailyAragings;
				this.agrmntTcs = agrmntTcs;
				this.agrmntMailingInfos = agrmntMailingInfos;
				this.agrmntSuppEmplInfos = agrmntSuppEmplInfos;
				this.agrmntColls = agrmntColls;
				this.agrmntAssets = agrmntAssets;
				this.payHistHdrs = payHistHdrs;
				this.paymentReceives = paymentReceives;
				this.agrmntInvoices = agrmntInvoices;
				this.agrmntCrossDefaultsForAgrmntId_1 = agrmntCrossDefaultsForAgrmntId_1;
				this.agrmntInses = agrmntInses;
				this.agrmntEmployeeInfos = agrmntEmployeeInfos;
			}
			
		@Id
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "AppId")
		public Application getApplication()
			{
				return this.application;
			}
			
		public void setApplication(Application application)
			{
				this.application = application;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "CurrencyID")
		public Currency getCurrency()
			{
				return this.currency;
			}
			
		public void setCurrency(Currency currency)
			{
				this.currency = currency;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "SpouseId")
		public Customer getCustomerBySpouseId()
			{
				return this.customerBySpouseId;
			}
			
		public void setCustomerBySpouseId(Customer customerBySpouseId)
			{
				this.customerBySpouseId = customerBySpouseId;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "GuarantorId")
		public Customer getCustomerByGuarantorId()
			{
				return this.customerByGuarantorId;
			}
			
		public void setCustomerByGuarantorId(Customer customerByGuarantorId)
			{
				this.customerByGuarantorId = customerByGuarantorId;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "CustomerID")
		public Customer getCustomerByCustomerId()
			{
				return this.customerByCustomerId;
			}
			
		public void setCustomerByCustomerId(Customer customerByCustomerId)
			{
				this.customerByCustomerId = customerByCustomerId;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "MarketingId")
		public Marketing getMarketing()
			{
				return this.marketing;
			}
			
		public void setMarketing(Marketing marketing)
			{
				this.marketing = marketing;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "OfficeId")
		public Office getOffice()
			{
				return this.office;
			}
			
		public void setOffice(Office office)
			{
				this.office = office;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "PartnerCode")
		public Partner getPartner()
			{
				return this.partner;
			}
			
		public void setPartner(Partner partner)
			{
				this.partner = partner;
			}
			
		@Column(name = "AgrmntCode", length = 20)
		public String getAgrmntCode()
			{
				return this.agrmntCode;
			}
			
		public void setAgrmntCode(String agrmntCode)
			{
				this.agrmntCode = agrmntCode;
			}
			
		@Column(name = "CoaSchmCode", length = 20)
		public String getCoaSchmCode()
			{
				return this.coaSchmCode;
			}
			
		public void setCoaSchmCode(String coaSchmCode)
			{
				this.coaSchmCode = coaSchmCode;
			}
			
		@Column(name = "ProdId")
		public Long getProdId()
			{
				return this.prodId;
			}
			
		public void setProdId(Long prodId)
			{
				this.prodId = prodId;
			}
			
		@Column(name = "PotId")
		public Long getPotId()
			{
				return this.potId;
			}
			
		public void setPotId(Long potId)
			{
				this.potId = potId;
			}
			
		@Column(name = "NumOfAsset")
		public Short getNumOfAsset()
			{
				return this.numOfAsset;
			}
			
		public void setNumOfAsset(Short numOfAsset)
			{
				this.numOfAsset = numOfAsset;
			}
			
		@Column(name = "InterestTypeCode", length = 20)
		public String getInterestTypeCode()
			{
				return this.interestTypeCode;
			}
			
		public void setInterestTypeCode(String interestTypeCode)
			{
				this.interestTypeCode = interestTypeCode;
			}
			
		@Column(name = "InstSchemeCode", length = 20)
		public String getInstSchemeCode()
			{
				return this.instSchemeCode;
			}
			
		public void setInstSchemeCode(String instSchemeCode)
			{
				this.instSchemeCode = instSchemeCode;
			}
			
		@Column(name = "GuarantorRelation", length = 50)
		public String getGuarantorRelation()
			{
				return this.guarantorRelation;
			}
			
		public void setGuarantorRelation(String guarantorRelation)
			{
				this.guarantorRelation = guarantorRelation;
			}
			
		@Column(name = "WopCode", length = 20)
		public String getWopCode()
			{
				return this.wopCode;
			}
			
		public void setWopCode(String wopCode)
			{
				this.wopCode = wopCode;
			}
			
		@Column(name = "SourceAppCode", length = 20)
		public String getSourceAppCode()
			{
				return this.sourceAppCode;
			}
			
		public void setSourceAppCode(String sourceAppCode)
			{
				this.sourceAppCode = sourceAppCode;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "AgreementDate", length = 23)
		public Date getAgreementDate()
			{
				return this.agreementDate;
			}
			
		public void setAgreementDate(Date agreementDate)
			{
				this.agreementDate = agreementDate;
			}
			
		@Column(name = "Notes", length = 8000)
		public String getNotes()
			{
				return this.notes;
			}
			
		public void setNotes(String notes)
			{
				this.notes = notes;
			}
			
		@Column(name = "OsP", precision = 53, scale = 0)
		public Double getOsP()
			{
				return this.osP;
			}
			
		public void setOsP(Double osP)
			{
				this.osP = osP;
			}
			
		@Column(name = "OsI", precision = 53, scale = 0)
		public Double getOsI()
			{
				return this.osI;
			}
			
		public void setOsI(Double osI)
			{
				this.osI = osI;
			}
			
		@Column(name = "OsPUndue", precision = 53, scale = 0)
		public Double getOsPundue()
			{
				return this.osPundue;
			}
			
		public void setOsPundue(Double osPundue)
			{
				this.osPundue = osPundue;
			}
			
		@Column(name = "OsIUndue", precision = 53, scale = 0)
		public Double getOsIundue()
			{
				return this.osIundue;
			}
			
		public void setOsIundue(Double osIundue)
			{
				this.osIundue = osIundue;
			}
			
		@Column(name = "InstAmount", precision = 53, scale = 0)
		public Double getInstAmount()
			{
				return this.instAmount;
			}
			
		public void setInstAmount(Double instAmount)
			{
				this.instAmount = instAmount;
			}
			
		@Column(name = "NextInstNumber")
		public Short getNextInstNumber()
			{
				return this.nextInstNumber;
			}
			
		public void setNextInstNumber(Short nextInstNumber)
			{
				this.nextInstNumber = nextInstNumber;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NextInstDate", length = 23)
		public Date getNextInstDate()
			{
				return this.nextInstDate;
			}
			
		public void setNextInstDate(Date nextInstDate)
			{
				this.nextInstDate = nextInstDate;
			}
			
		@Column(name = "NextInstDueNumber")
		public Short getNextInstDueNumber()
			{
				return this.nextInstDueNumber;
			}
			
		public void setNextInstDueNumber(Short nextInstDueNumber)
			{
				this.nextInstDueNumber = nextInstDueNumber;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NextInstDueDate", length = 23)
		public Date getNextInstDueDate()
			{
				return this.nextInstDueDate;
			}
			
		public void setNextInstDueDate(Date nextInstDueDate)
			{
				this.nextInstDueDate = nextInstDueDate;
			}
			
		@Column(name = "PrepaidAmt", precision = 53, scale = 0)
		public Double getPrepaidAmt()
			{
				return this.prepaidAmt;
			}
			
		public void setPrepaidAmt(Double prepaidAmt)
			{
				this.prepaidAmt = prepaidAmt;
			}
			
		@Column(name = "Tenor")
		public Short getTenor()
			{
				return this.tenor;
			}
			
		public void setTenor(Short tenor)
			{
				this.tenor = tenor;
			}
			
		@Column(name = "CummulativeTenor")
		public Short getCummulativeTenor()
			{
				return this.cummulativeTenor;
			}
			
		public void setCummulativeTenor(Short cummulativeTenor)
			{
				this.cummulativeTenor = cummulativeTenor;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "EffectiveDate", length = 23)
		public Date getEffectiveDate()
			{
				return this.effectiveDate;
			}
			
		public void setEffectiveDate(Date effectiveDate)
			{
				this.effectiveDate = effectiveDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "GoLiveDate", length = 23)
		public Date getGoLiveDate()
			{
				return this.goLiveDate;
			}
			
		public void setGoLiveDate(Date goLiveDate)
			{
				this.goLiveDate = goLiveDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "RRDDate", length = 23)
		public Date getRrddate()
			{
				return this.rrddate;
			}
			
		public void setRrddate(Date rrddate)
			{
				this.rrddate = rrddate;
			}
			
		@Column(name = "ContractStatus", length = 3)
		public String getContractStatus()
			{
				return this.contractStatus;
			}
			
		public void setContractStatus(String contractStatus)
			{
				this.contractStatus = contractStatus;
			}
			
		@Column(name = "DefaultStatus", length = 5)
		public String getDefaultStatus()
			{
				return this.defaultStatus;
			}
			
		public void setDefaultStatus(String defaultStatus)
			{
				this.defaultStatus = defaultStatus;
			}
			
		@Column(name = "PercentagePenalty", precision = 53, scale = 0)
		public Double getPercentagePenalty()
			{
				return this.percentagePenalty;
			}
			
		public void setPercentagePenalty(Double percentagePenalty)
			{
				this.percentagePenalty = percentagePenalty;
			}
			
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PdcHdr> getPdcHdrs()
			{
				return this.pdcHdrs;
			}
			
		public void setPdcHdrs(Set<PdcHdr> pdcHdrs)
			{
				this.pdcHdrs = pdcHdrs;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<SuspendAllocation> getSuspendAllocations()
			{
				return this.suspendAllocations;
			}
			
		public void setSuspendAllocations(Set<SuspendAllocation> suspendAllocations)
			{
				this.suspendAllocations = suspendAllocations;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntMnt> getAgrmntMnts()
			{
				return this.agrmntMnts;
			}
			
		public void setAgrmntMnts(Set<AgrmntMnt> agrmntMnts)
			{
				this.agrmntMnts = agrmntMnts;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntFund> getAgrmntFunds()
			{
				return this.agrmntFunds;
			}
			
		public void setAgrmntFunds(Set<AgrmntFund> agrmntFunds)
			{
				this.agrmntFunds = agrmntFunds;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<InstSchedule> getInstSchedules()
			{
				return this.instSchedules;
			}
			
		public void setInstSchedules(Set<InstSchedule> instSchedules)
			{
				this.instSchedules = instSchedules;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntBankStatementInfo> getAgrmntBankStatementInfos()
			{
				return this.agrmntBankStatementInfos;
			}
			
		public void setAgrmntBankStatementInfos(Set<AgrmntBankStatementInfo> agrmntBankStatementInfos)
			{
				this.agrmntBankStatementInfos = agrmntBankStatementInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntReffInfo> getAgrmntReffInfos()
			{
				return this.agrmntReffInfos;
			}
			
		public void setAgrmntReffInfos(Set<AgrmntReffInfo> agrmntReffInfos)
			{
				this.agrmntReffInfos = agrmntReffInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmntByAgrmntId")
		public Set<AgrmntCrossDefault> getAgrmntCrossDefaultsForAgrmntId()
			{
				return this.agrmntCrossDefaultsForAgrmntId;
			}
			
		public void setAgrmntCrossDefaultsForAgrmntId(Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId)
			{
				this.agrmntCrossDefaultsForAgrmntId = agrmntCrossDefaultsForAgrmntId;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PaymentReversal> getPaymentReversals()
			{
				return this.paymentReversals;
			}
			
		public void setPaymentReversals(Set<PaymentReversal> paymentReversals)
			{
				this.paymentReversals = paymentReversals;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmntByCrossAgrmntId")
		public Set<AgrmntCrossDefault> getAgrmntCrossDefaultsForCrossAgrmntId()
			{
				return this.agrmntCrossDefaultsForCrossAgrmntId;
			}
			
		public void setAgrmntCrossDefaultsForCrossAgrmntId(Set<AgrmntCrossDefault> agrmntCrossDefaultsForCrossAgrmntId)
			{
				this.agrmntCrossDefaultsForCrossAgrmntId = agrmntCrossDefaultsForCrossAgrmntId;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<DeliveryOrder> getDeliveryOrders()
			{
				return this.deliveryOrders;
			}
			
		public void setDeliveryOrders(Set<DeliveryOrder> deliveryOrders)
			{
				this.deliveryOrders = deliveryOrders;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<EarlyTermination> getEarlyTerminations()
			{
				return this.earlyTerminations;
			}
			
		public void setEarlyTerminations(Set<EarlyTermination> earlyTerminations)
			{
				this.earlyTerminations = earlyTerminations;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntGoLive> getAgrmntGoLives()
			{
				return this.agrmntGoLives;
			}
			
		public void setAgrmntGoLives(Set<AgrmntGoLive> agrmntGoLives)
			{
				this.agrmntGoLives = agrmntGoLives;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<DailyAraging> getDailyAragings()
			{
				return this.dailyAragings;
			}
			
		public void setDailyAragings(Set<DailyAraging> dailyAragings)
			{
				this.dailyAragings = dailyAragings;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntTc> getAgrmntTcs()
			{
				return this.agrmntTcs;
			}
			
		public void setAgrmntTcs(Set<AgrmntTc> agrmntTcs)
			{
				this.agrmntTcs = agrmntTcs;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntMailingInfo> getAgrmntMailingInfos()
			{
				return this.agrmntMailingInfos;
			}
			
		public void setAgrmntMailingInfos(Set<AgrmntMailingInfo> agrmntMailingInfos)
			{
				this.agrmntMailingInfos = agrmntMailingInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntSuppEmplInfo> getAgrmntSuppEmplInfos()
			{
				return this.agrmntSuppEmplInfos;
			}
			
		public void setAgrmntSuppEmplInfos(Set<AgrmntSuppEmplInfo> agrmntSuppEmplInfos)
			{
				this.agrmntSuppEmplInfos = agrmntSuppEmplInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntColl> getAgrmntColls()
			{
				return this.agrmntColls;
			}
			
		public void setAgrmntColls(Set<AgrmntColl> agrmntColls)
			{
				this.agrmntColls = agrmntColls;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntAsset> getAgrmntAssets()
			{
				return this.agrmntAssets;
			}
			
		public void setAgrmntAssets(Set<AgrmntAsset> agrmntAssets)
			{
				this.agrmntAssets = agrmntAssets;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PayHistHdr> getPayHistHdrs()
			{
				return this.payHistHdrs;
			}
			
		public void setPayHistHdrs(Set<PayHistHdr> payHistHdrs)
			{
				this.payHistHdrs = payHistHdrs;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PaymentReceive> getPaymentReceives()
			{
				return this.paymentReceives;
			}
			
		public void setPaymentReceives(Set<PaymentReceive> paymentReceives)
			{
				this.paymentReceives = paymentReceives;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntInvoice> getAgrmntInvoices()
			{
				return this.agrmntInvoices;
			}
			
		public void setAgrmntInvoices(Set<AgrmntInvoice> agrmntInvoices)
			{
				this.agrmntInvoices = agrmntInvoices;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmntByAgrmntId")
		public Set<AgrmntCrossDefault> getAgrmntCrossDefaultsForAgrmntId_1()
			{
				return this.agrmntCrossDefaultsForAgrmntId_1;
			}
			
		public void setAgrmntCrossDefaultsForAgrmntId_1(Set<AgrmntCrossDefault> agrmntCrossDefaultsForAgrmntId_1)
			{
				this.agrmntCrossDefaultsForAgrmntId_1 = agrmntCrossDefaultsForAgrmntId_1;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntIns> getAgrmntInses()
			{
				return this.agrmntInses;
			}
			
		public void setAgrmntInses(Set<AgrmntIns> agrmntInses)
			{
				this.agrmntInses = agrmntInses;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntEmployeeInfo> getAgrmntEmployeeInfos()
			{
				return this.agrmntEmployeeInfos;
			}
			
		public void setAgrmntEmployeeInfos(Set<AgrmntEmployeeInfo> agrmntEmployeeInfos)
			{
				this.agrmntEmployeeInfos = agrmntEmployeeInfos;
			}
			
	}
