
package com.adibrata.smartdealer.model;
// Generated Jul 23, 2015 8:14:47 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agrmnt generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "Agrmnt", catalog = "SmartDealer")
public class Agrmnt implements java.io.Serializable
	{
		
		private long id;
		private Application application;
		private Customer customer;
		private Office office;
		private Partner partner;
		private String agrmntCode;
		private String coaSchmCode;
		private long productId;
		private long productOfferingId;
		private long currencyId;
		private Short numOfAssetUnit;
		private Short tenor;
		private Date effectiveDate;
		private String interestType;
		private String installmentScheme;
		private String stepUpStepDownType;
		private short cummulativeTenor;
		private String insAssetInsuredBy;
		private String insAssetPaidBy;
		private String insAssetPeriod;
		private Long guarantorId;
		private String guarantorRelationship;
		private Long spouseId;
		private String wayOfPayment;
		private Date agreementDate;
		private Short isSurveyResidenceAddress;
		private Date newApplicationDate;
		private Date creditScoringDate;
		private Long supplierId;
		private String applicationSource;
		private double insAssetPremium;
		private double insAssetReceivedInAdv;
		private double insAssetAddPremium;
		private double insAssetCapitalized;
		private Double insRefundToSupplier;
		private Double insRefundToSupplierPaid;
		private Double insRefundToSupplierInProcess;
		private double totalOtr;
		private double downPayment;
		private double ntf;
		private double effectiveRate;
		private double flatRate;
		private double supplierRate;
		private double standardRate;
		private double grossYieldStandard;
		private String paymentFrequency;
		private String firstInstallment;
		private short numOfAdvanceInstallment;
		private short numOfInstallment;
		private double installmentAmount;
		private short gracePeriod;
		private String gracePeriodType;
		private short gracePeriodLc;
		private double grossYield;
		private double percentagePenalty;
		private double adminFee;
		private Double adminFeePercentage;
		private double addAdminFee;
		private double fiduciaFee;
		private double provisionFee;
		private double notaryFee;
		private double surveyFee;
		private double otherFee;
		private String crossDefaultApplicationId;
		private String notes;
		private double diffRateAmount;
		private double diffRateStdAmount;
		private double creditScore;
		private String creditScoringResult;
		private String financeType;
		private String productType;
		private String contractStatus;
		private String defaultStatus;
		private String applicationStep;
		private double osp;
		private double osi;
		private double ospundue;
		private double osiundue;
		private Date nextInstDate;
		private short nextInstNumber;
		private Date nextInstDueDate;
		private short nextInstDueNumber;
		private double tdpamount;
		private Double prepaidAmt;
		private Short isSyariah;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private String usrCrt;
		private Set<GoLive> goLives = new HashSet<GoLive>(0);
		private Set<AgrmntMnt> agrmntMnts = new HashSet<AgrmntMnt>(0);
		private Set<AgrmntFund> agrmntFunds = new HashSet<AgrmntFund>(0);
		private Set<InstSchedule> instSchedules = new HashSet<InstSchedule>(0);
		private Set<AgrmntColl> agrmntColls = new HashSet<AgrmntColl>(0);
		private Set<AgrmntAsset> agrmntAssets = new HashSet<AgrmntAsset>(0);
		private Set<AgrmntBankStatementInfo> agrmntBankStatementInfos = new HashSet<AgrmntBankStatementInfo>(0);
		private Set<AgrmntReffInfo> agrmntReffInfos = new HashSet<AgrmntReffInfo>(0);
		private Set<PayHistHdr> payHistHdrs = new HashSet<PayHistHdr>(0);
		private Set<PaymentReceive> paymentReceives = new HashSet<PaymentReceive>(0);
		private Set<AgrmntEmployee> agrmntEmployees = new HashSet<AgrmntEmployee>(0);
		private Set<AgrmntIns> agrmntInses = new HashSet<AgrmntIns>(0);
		private Set<AgrmntBankStatementInfo> agrmntBankStatementInfos_1 = new HashSet<AgrmntBankStatementInfo>(0);
		private Set<AgrmntEmployeeInfo> agrmntEmployeeInfos = new HashSet<AgrmntEmployeeInfo>(0);
		private Set<AgrmntMailingInfo> agrmntMailingInfos = new HashSet<AgrmntMailingInfo>(0);
		
		public Agrmnt()
			{
			}
			
		public Agrmnt(long id, long productId, long productOfferingId, long currencyId, String interestType, String installmentScheme, short cummulativeTenor, String wayOfPayment, String applicationSource, double insAssetPremium,
		        double insAssetReceivedInAdv, double insAssetAddPremium, double insAssetCapitalized, double totalOtr, double downPayment, double ntf, double effectiveRate, double flatRate, double supplierRate, double standardRate,
		        double grossYieldStandard, short numOfAdvanceInstallment, short numOfInstallment, double installmentAmount, short gracePeriod, short gracePeriodLc, double grossYield, double percentagePenalty, double adminFee, double addAdminFee,
		        double fiduciaFee, double provisionFee, double notaryFee, double surveyFee, double otherFee, double diffRateAmount, double diffRateStdAmount, double creditScore, String financeType, String productType, String contractStatus,
		        String defaultStatus, String applicationStep, double osp, double osi, double ospundue, double osiundue, short nextInstNumber, short nextInstDueNumber, double tdpamount)
			{
				this.id = id;
				this.productId = productId;
				this.productOfferingId = productOfferingId;
				this.currencyId = currencyId;
				this.interestType = interestType;
				this.installmentScheme = installmentScheme;
				this.cummulativeTenor = cummulativeTenor;
				this.wayOfPayment = wayOfPayment;
				this.applicationSource = applicationSource;
				this.insAssetPremium = insAssetPremium;
				this.insAssetReceivedInAdv = insAssetReceivedInAdv;
				this.insAssetAddPremium = insAssetAddPremium;
				this.insAssetCapitalized = insAssetCapitalized;
				this.totalOtr = totalOtr;
				this.downPayment = downPayment;
				this.ntf = ntf;
				this.effectiveRate = effectiveRate;
				this.flatRate = flatRate;
				this.supplierRate = supplierRate;
				this.standardRate = standardRate;
				this.grossYieldStandard = grossYieldStandard;
				this.numOfAdvanceInstallment = numOfAdvanceInstallment;
				this.numOfInstallment = numOfInstallment;
				this.installmentAmount = installmentAmount;
				this.gracePeriod = gracePeriod;
				this.gracePeriodLc = gracePeriodLc;
				this.grossYield = grossYield;
				this.percentagePenalty = percentagePenalty;
				this.adminFee = adminFee;
				this.addAdminFee = addAdminFee;
				this.fiduciaFee = fiduciaFee;
				this.provisionFee = provisionFee;
				this.notaryFee = notaryFee;
				this.surveyFee = surveyFee;
				this.otherFee = otherFee;
				this.diffRateAmount = diffRateAmount;
				this.diffRateStdAmount = diffRateStdAmount;
				this.creditScore = creditScore;
				this.financeType = financeType;
				this.productType = productType;
				this.contractStatus = contractStatus;
				this.defaultStatus = defaultStatus;
				this.applicationStep = applicationStep;
				this.osp = osp;
				this.osi = osi;
				this.ospundue = ospundue;
				this.osiundue = osiundue;
				this.nextInstNumber = nextInstNumber;
				this.nextInstDueNumber = nextInstDueNumber;
				this.tdpamount = tdpamount;
			}
			
		public Agrmnt(long id, Application application, Customer customer, Office office, Partner partner, String agrmntCode, String coaSchmCode, long productId, long productOfferingId, long currencyId, Short numOfAssetUnit, Short tenor,
		        Date effectiveDate, String interestType, String installmentScheme, String stepUpStepDownType, short cummulativeTenor, String insAssetInsuredBy, String insAssetPaidBy, String insAssetPeriod, Long guarantorId,
		        String guarantorRelationship, Long spouseId, String wayOfPayment, Date agreementDate, Short isSurveyResidenceAddress, Date newApplicationDate, Date creditScoringDate, Long supplierId, String applicationSource, double insAssetPremium,
		        double insAssetReceivedInAdv, double insAssetAddPremium, double insAssetCapitalized, Double insRefundToSupplier, Double insRefundToSupplierPaid, Double insRefundToSupplierInProcess, double totalOtr, double downPayment, double ntf,
		        double effectiveRate, double flatRate, double supplierRate, double standardRate, double grossYieldStandard, String paymentFrequency, String firstInstallment, short numOfAdvanceInstallment, short numOfInstallment,
		        double installmentAmount, short gracePeriod, String gracePeriodType, short gracePeriodLc, double grossYield, double percentagePenalty, double adminFee, Double adminFeePercentage, double addAdminFee, double fiduciaFee,
		        double provisionFee, double notaryFee, double surveyFee, double otherFee, String crossDefaultApplicationId, String notes, double diffRateAmount, double diffRateStdAmount, double creditScore, String creditScoringResult,
		        String financeType, String productType, String contractStatus, String defaultStatus, String applicationStep, double osp, double osi, double ospundue, double osiundue, Date nextInstDate, short nextInstNumber, Date nextInstDueDate,
		        short nextInstDueNumber, double tdpamount, Double prepaidAmt, Short isSyariah, Date dtmUpd, String usrUpd, Date dtmCrt, String usrCrt, Set<GoLive> goLives, Set<AgrmntMnt> agrmntMnts, Set<AgrmntFund> agrmntFunds,
		        Set<InstSchedule> instSchedules, Set<AgrmntColl> agrmntColls, Set<AgrmntAsset> agrmntAssets, Set<AgrmntBankStatementInfo> agrmntBankStatementInfos, Set<AgrmntReffInfo> agrmntReffInfos, Set<PayHistHdr> payHistHdrs,
		        Set<PaymentReceive> paymentReceives, Set<AgrmntEmployee> agrmntEmployees, Set<AgrmntIns> agrmntInses, Set<AgrmntBankStatementInfo> agrmntBankStatementInfos_1, Set<AgrmntEmployeeInfo> agrmntEmployeeInfos,
		        Set<AgrmntMailingInfo> agrmntMailingInfos)
			{
				this.id = id;
				this.application = application;
				this.customer = customer;
				this.office = office;
				this.partner = partner;
				this.agrmntCode = agrmntCode;
				this.coaSchmCode = coaSchmCode;
				this.productId = productId;
				this.productOfferingId = productOfferingId;
				this.currencyId = currencyId;
				this.numOfAssetUnit = numOfAssetUnit;
				this.tenor = tenor;
				this.effectiveDate = effectiveDate;
				this.interestType = interestType;
				this.installmentScheme = installmentScheme;
				this.stepUpStepDownType = stepUpStepDownType;
				this.cummulativeTenor = cummulativeTenor;
				this.insAssetInsuredBy = insAssetInsuredBy;
				this.insAssetPaidBy = insAssetPaidBy;
				this.insAssetPeriod = insAssetPeriod;
				this.guarantorId = guarantorId;
				this.guarantorRelationship = guarantorRelationship;
				this.spouseId = spouseId;
				this.wayOfPayment = wayOfPayment;
				this.agreementDate = agreementDate;
				this.isSurveyResidenceAddress = isSurveyResidenceAddress;
				this.newApplicationDate = newApplicationDate;
				this.creditScoringDate = creditScoringDate;
				this.supplierId = supplierId;
				this.applicationSource = applicationSource;
				this.insAssetPremium = insAssetPremium;
				this.insAssetReceivedInAdv = insAssetReceivedInAdv;
				this.insAssetAddPremium = insAssetAddPremium;
				this.insAssetCapitalized = insAssetCapitalized;
				this.insRefundToSupplier = insRefundToSupplier;
				this.insRefundToSupplierPaid = insRefundToSupplierPaid;
				this.insRefundToSupplierInProcess = insRefundToSupplierInProcess;
				this.totalOtr = totalOtr;
				this.downPayment = downPayment;
				this.ntf = ntf;
				this.effectiveRate = effectiveRate;
				this.flatRate = flatRate;
				this.supplierRate = supplierRate;
				this.standardRate = standardRate;
				this.grossYieldStandard = grossYieldStandard;
				this.paymentFrequency = paymentFrequency;
				this.firstInstallment = firstInstallment;
				this.numOfAdvanceInstallment = numOfAdvanceInstallment;
				this.numOfInstallment = numOfInstallment;
				this.installmentAmount = installmentAmount;
				this.gracePeriod = gracePeriod;
				this.gracePeriodType = gracePeriodType;
				this.gracePeriodLc = gracePeriodLc;
				this.grossYield = grossYield;
				this.percentagePenalty = percentagePenalty;
				this.adminFee = adminFee;
				this.adminFeePercentage = adminFeePercentage;
				this.addAdminFee = addAdminFee;
				this.fiduciaFee = fiduciaFee;
				this.provisionFee = provisionFee;
				this.notaryFee = notaryFee;
				this.surveyFee = surveyFee;
				this.otherFee = otherFee;
				this.crossDefaultApplicationId = crossDefaultApplicationId;
				this.notes = notes;
				this.diffRateAmount = diffRateAmount;
				this.diffRateStdAmount = diffRateStdAmount;
				this.creditScore = creditScore;
				this.creditScoringResult = creditScoringResult;
				this.financeType = financeType;
				this.productType = productType;
				this.contractStatus = contractStatus;
				this.defaultStatus = defaultStatus;
				this.applicationStep = applicationStep;
				this.osp = osp;
				this.osi = osi;
				this.ospundue = ospundue;
				this.osiundue = osiundue;
				this.nextInstDate = nextInstDate;
				this.nextInstNumber = nextInstNumber;
				this.nextInstDueDate = nextInstDueDate;
				this.nextInstDueNumber = nextInstDueNumber;
				this.tdpamount = tdpamount;
				this.prepaidAmt = prepaidAmt;
				this.isSyariah = isSyariah;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.usrCrt = usrCrt;
				this.goLives = goLives;
				this.agrmntMnts = agrmntMnts;
				this.agrmntFunds = agrmntFunds;
				this.instSchedules = instSchedules;
				this.agrmntColls = agrmntColls;
				this.agrmntAssets = agrmntAssets;
				this.agrmntBankStatementInfos = agrmntBankStatementInfos;
				this.agrmntReffInfos = agrmntReffInfos;
				this.payHistHdrs = payHistHdrs;
				this.paymentReceives = paymentReceives;
				this.agrmntEmployees = agrmntEmployees;
				this.agrmntInses = agrmntInses;
				this.agrmntBankStatementInfos_1 = agrmntBankStatementInfos_1;
				this.agrmntEmployeeInfos = agrmntEmployeeInfos;
				this.agrmntMailingInfos = agrmntMailingInfos;
			}
			
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "AppId")
		public Application getApplication()
			{
				return this.application;
			}
			
		public void setApplication(Application application)
			{
				this.application = application;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "CustomerId")
		public Customer getCustomer()
			{
				return this.customer;
			}
			
		public void setCustomer(Customer customer)
			{
				this.customer = customer;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "OfficeId")
		public Office getOffice()
			{
				return this.office;
			}
			
		public void setOffice(Office office)
			{
				this.office = office;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "PartnerCode")
		public Partner getPartner()
			{
				return this.partner;
			}
			
		public void setPartner(Partner partner)
			{
				this.partner = partner;
			}
			
		@Column(name = "AgrmntCode", length = 20)
		public String getAgrmntCode()
			{
				return this.agrmntCode;
			}
			
		public void setAgrmntCode(String agrmntCode)
			{
				this.agrmntCode = agrmntCode;
			}
			
		@Column(name = "CoaSchmCode", length = 20)
		public String getCoaSchmCode()
			{
				return this.coaSchmCode;
			}
			
		public void setCoaSchmCode(String coaSchmCode)
			{
				this.coaSchmCode = coaSchmCode;
			}
			
		@Column(name = "ProductID", nullable = false)
		public long getProductId()
			{
				return this.productId;
			}
			
		public void setProductId(long productId)
			{
				this.productId = productId;
			}
			
		@Column(name = "ProductOfferingID", nullable = false)
		public long getProductOfferingId()
			{
				return this.productOfferingId;
			}
			
		public void setProductOfferingId(long productOfferingId)
			{
				this.productOfferingId = productOfferingId;
			}
			
		@Column(name = "CurrencyID", nullable = false)
		public long getCurrencyId()
			{
				return this.currencyId;
			}
			
		public void setCurrencyId(long currencyId)
			{
				this.currencyId = currencyId;
			}
			
		@Column(name = "NumOfAssetUnit")
		public Short getNumOfAssetUnit()
			{
				return this.numOfAssetUnit;
			}
			
		public void setNumOfAssetUnit(Short numOfAssetUnit)
			{
				this.numOfAssetUnit = numOfAssetUnit;
			}
			
		@Column(name = "Tenor")
		public Short getTenor()
			{
				return this.tenor;
			}
			
		public void setTenor(Short tenor)
			{
				this.tenor = tenor;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "EffectiveDate", length = 23)
		public Date getEffectiveDate()
			{
				return this.effectiveDate;
			}
			
		public void setEffectiveDate(Date effectiveDate)
			{
				this.effectiveDate = effectiveDate;
			}
			
		@Column(name = "InterestType", nullable = false, length = 2)
		public String getInterestType()
			{
				return this.interestType;
			}
			
		public void setInterestType(String interestType)
			{
				this.interestType = interestType;
			}
			
		@Column(name = "InstallmentScheme", nullable = false, length = 2)
		public String getInstallmentScheme()
			{
				return this.installmentScheme;
			}
			
		public void setInstallmentScheme(String installmentScheme)
			{
				this.installmentScheme = installmentScheme;
			}
			
		@Column(name = "StepUpStepDownType", length = 2)
		public String getStepUpStepDownType()
			{
				return this.stepUpStepDownType;
			}
			
		public void setStepUpStepDownType(String stepUpStepDownType)
			{
				this.stepUpStepDownType = stepUpStepDownType;
			}
			
		@Column(name = "CummulativeTenor", nullable = false)
		public short getCummulativeTenor()
			{
				return this.cummulativeTenor;
			}
			
		public void setCummulativeTenor(short cummulativeTenor)
			{
				this.cummulativeTenor = cummulativeTenor;
			}
			
		@Column(name = "InsAssetInsuredBy", length = 10)
		public String getInsAssetInsuredBy()
			{
				return this.insAssetInsuredBy;
			}
			
		public void setInsAssetInsuredBy(String insAssetInsuredBy)
			{
				this.insAssetInsuredBy = insAssetInsuredBy;
			}
			
		@Column(name = "InsAssetPaidBy", length = 10)
		public String getInsAssetPaidBy()
			{
				return this.insAssetPaidBy;
			}
			
		public void setInsAssetPaidBy(String insAssetPaidBy)
			{
				this.insAssetPaidBy = insAssetPaidBy;
			}
			
		@Column(name = "InsAssetPeriod", length = 2)
		public String getInsAssetPeriod()
			{
				return this.insAssetPeriod;
			}
			
		public void setInsAssetPeriod(String insAssetPeriod)
			{
				this.insAssetPeriod = insAssetPeriod;
			}
			
		@Column(name = "GuarantorID")
		public Long getGuarantorId()
			{
				return this.guarantorId;
			}
			
		public void setGuarantorId(Long guarantorId)
			{
				this.guarantorId = guarantorId;
			}
			
		@Column(name = "GuarantorRelationship", length = 20)
		public String getGuarantorRelationship()
			{
				return this.guarantorRelationship;
			}
			
		public void setGuarantorRelationship(String guarantorRelationship)
			{
				this.guarantorRelationship = guarantorRelationship;
			}
			
		@Column(name = "SpouseID")
		public Long getSpouseId()
			{
				return this.spouseId;
			}
			
		public void setSpouseId(Long spouseId)
			{
				this.spouseId = spouseId;
			}
			
		@Column(name = "WayOfPayment", nullable = false, length = 2)
		public String getWayOfPayment()
			{
				return this.wayOfPayment;
			}
			
		public void setWayOfPayment(String wayOfPayment)
			{
				this.wayOfPayment = wayOfPayment;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "AgreementDate", length = 23)
		public Date getAgreementDate()
			{
				return this.agreementDate;
			}
			
		public void setAgreementDate(Date agreementDate)
			{
				this.agreementDate = agreementDate;
			}
			
		@Column(name = "IsSurveyResidenceAddress")
		public Short getIsSurveyResidenceAddress()
			{
				return this.isSurveyResidenceAddress;
			}
			
		public void setIsSurveyResidenceAddress(Short isSurveyResidenceAddress)
			{
				this.isSurveyResidenceAddress = isSurveyResidenceAddress;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NewApplicationDate", length = 23)
		public Date getNewApplicationDate()
			{
				return this.newApplicationDate;
			}
			
		public void setNewApplicationDate(Date newApplicationDate)
			{
				this.newApplicationDate = newApplicationDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "CreditScoringDate", length = 23)
		public Date getCreditScoringDate()
			{
				return this.creditScoringDate;
			}
			
		public void setCreditScoringDate(Date creditScoringDate)
			{
				this.creditScoringDate = creditScoringDate;
			}
			
		@Column(name = "SupplierID")
		public Long getSupplierId()
			{
				return this.supplierId;
			}
			
		public void setSupplierId(Long supplierId)
			{
				this.supplierId = supplierId;
			}
			
		@Column(name = "ApplicationSource", nullable = false, length = 50)
		public String getApplicationSource()
			{
				return this.applicationSource;
			}
			
		public void setApplicationSource(String applicationSource)
			{
				this.applicationSource = applicationSource;
			}
			
		@Column(name = "InsAssetPremium", nullable = false, precision = 53, scale = 0)
		public double getInsAssetPremium()
			{
				return this.insAssetPremium;
			}
			
		public void setInsAssetPremium(double insAssetPremium)
			{
				this.insAssetPremium = insAssetPremium;
			}
			
		@Column(name = "InsAssetReceivedInAdv", nullable = false, precision = 53, scale = 0)
		public double getInsAssetReceivedInAdv()
			{
				return this.insAssetReceivedInAdv;
			}
			
		public void setInsAssetReceivedInAdv(double insAssetReceivedInAdv)
			{
				this.insAssetReceivedInAdv = insAssetReceivedInAdv;
			}
			
		@Column(name = "InsAssetAddPremium", nullable = false, precision = 53, scale = 0)
		public double getInsAssetAddPremium()
			{
				return this.insAssetAddPremium;
			}
			
		public void setInsAssetAddPremium(double insAssetAddPremium)
			{
				this.insAssetAddPremium = insAssetAddPremium;
			}
			
		@Column(name = "InsAssetCapitalized", nullable = false, precision = 53, scale = 0)
		public double getInsAssetCapitalized()
			{
				return this.insAssetCapitalized;
			}
			
		public void setInsAssetCapitalized(double insAssetCapitalized)
			{
				this.insAssetCapitalized = insAssetCapitalized;
			}
			
		@Column(name = "InsRefundToSupplier", precision = 53, scale = 0)
		public Double getInsRefundToSupplier()
			{
				return this.insRefundToSupplier;
			}
			
		public void setInsRefundToSupplier(Double insRefundToSupplier)
			{
				this.insRefundToSupplier = insRefundToSupplier;
			}
			
		@Column(name = "InsRefundToSupplierPaid", precision = 53, scale = 0)
		public Double getInsRefundToSupplierPaid()
			{
				return this.insRefundToSupplierPaid;
			}
			
		public void setInsRefundToSupplierPaid(Double insRefundToSupplierPaid)
			{
				this.insRefundToSupplierPaid = insRefundToSupplierPaid;
			}
			
		@Column(name = "InsRefundToSupplierInProcess", precision = 53, scale = 0)
		public Double getInsRefundToSupplierInProcess()
			{
				return this.insRefundToSupplierInProcess;
			}
			
		public void setInsRefundToSupplierInProcess(Double insRefundToSupplierInProcess)
			{
				this.insRefundToSupplierInProcess = insRefundToSupplierInProcess;
			}
			
		@Column(name = "TotalOTR", nullable = false, precision = 53, scale = 0)
		public double getTotalOtr()
			{
				return this.totalOtr;
			}
			
		public void setTotalOtr(double totalOtr)
			{
				this.totalOtr = totalOtr;
			}
			
		@Column(name = "DownPayment", nullable = false, precision = 53, scale = 0)
		public double getDownPayment()
			{
				return this.downPayment;
			}
			
		public void setDownPayment(double downPayment)
			{
				this.downPayment = downPayment;
			}
			
		@Column(name = "NTF", nullable = false, precision = 53, scale = 0)
		public double getNtf()
			{
				return this.ntf;
			}
			
		public void setNtf(double ntf)
			{
				this.ntf = ntf;
			}
			
		@Column(name = "EffectiveRate", nullable = false, precision = 53, scale = 0)
		public double getEffectiveRate()
			{
				return this.effectiveRate;
			}
			
		public void setEffectiveRate(double effectiveRate)
			{
				this.effectiveRate = effectiveRate;
			}
			
		@Column(name = "FlatRate", nullable = false, precision = 53, scale = 0)
		public double getFlatRate()
			{
				return this.flatRate;
			}
			
		public void setFlatRate(double flatRate)
			{
				this.flatRate = flatRate;
			}
			
		@Column(name = "SupplierRate", nullable = false, precision = 53, scale = 0)
		public double getSupplierRate()
			{
				return this.supplierRate;
			}
			
		public void setSupplierRate(double supplierRate)
			{
				this.supplierRate = supplierRate;
			}
			
		@Column(name = "StandardRate", nullable = false, precision = 53, scale = 0)
		public double getStandardRate()
			{
				return this.standardRate;
			}
			
		public void setStandardRate(double standardRate)
			{
				this.standardRate = standardRate;
			}
			
		@Column(name = "GrossYieldStandard", nullable = false, precision = 53, scale = 0)
		public double getGrossYieldStandard()
			{
				return this.grossYieldStandard;
			}
			
		public void setGrossYieldStandard(double grossYieldStandard)
			{
				this.grossYieldStandard = grossYieldStandard;
			}
			
		@Column(name = "PaymentFrequency", length = 1)
		public String getPaymentFrequency()
			{
				return this.paymentFrequency;
			}
			
		public void setPaymentFrequency(String paymentFrequency)
			{
				this.paymentFrequency = paymentFrequency;
			}
			
		@Column(name = "FirstInstallment", length = 2)
		public String getFirstInstallment()
			{
				return this.firstInstallment;
			}
			
		public void setFirstInstallment(String firstInstallment)
			{
				this.firstInstallment = firstInstallment;
			}
			
		@Column(name = "NumOfAdvanceInstallment", nullable = false)
		public short getNumOfAdvanceInstallment()
			{
				return this.numOfAdvanceInstallment;
			}
			
		public void setNumOfAdvanceInstallment(short numOfAdvanceInstallment)
			{
				this.numOfAdvanceInstallment = numOfAdvanceInstallment;
			}
			
		@Column(name = "NumOfInstallment", nullable = false)
		public short getNumOfInstallment()
			{
				return this.numOfInstallment;
			}
			
		public void setNumOfInstallment(short numOfInstallment)
			{
				this.numOfInstallment = numOfInstallment;
			}
			
		@Column(name = "InstallmentAmount", nullable = false, precision = 53, scale = 0)
		public double getInstallmentAmount()
			{
				return this.installmentAmount;
			}
			
		public void setInstallmentAmount(double installmentAmount)
			{
				this.installmentAmount = installmentAmount;
			}
			
		@Column(name = "GracePeriod", nullable = false)
		public short getGracePeriod()
			{
				return this.gracePeriod;
			}
			
		public void setGracePeriod(short gracePeriod)
			{
				this.gracePeriod = gracePeriod;
			}
			
		@Column(name = "GracePeriodType", length = 1)
		public String getGracePeriodType()
			{
				return this.gracePeriodType;
			}
			
		public void setGracePeriodType(String gracePeriodType)
			{
				this.gracePeriodType = gracePeriodType;
			}
			
		@Column(name = "GracePeriodLC", nullable = false)
		public short getGracePeriodLc()
			{
				return this.gracePeriodLc;
			}
			
		public void setGracePeriodLc(short gracePeriodLc)
			{
				this.gracePeriodLc = gracePeriodLc;
			}
			
		@Column(name = "GrossYield", nullable = false, precision = 53, scale = 0)
		public double getGrossYield()
			{
				return this.grossYield;
			}
			
		public void setGrossYield(double grossYield)
			{
				this.grossYield = grossYield;
			}
			
		@Column(name = "PercentagePenalty", nullable = false, precision = 53, scale = 0)
		public double getPercentagePenalty()
			{
				return this.percentagePenalty;
			}
			
		public void setPercentagePenalty(double percentagePenalty)
			{
				this.percentagePenalty = percentagePenalty;
			}
			
		@Column(name = "AdminFee", nullable = false, precision = 53, scale = 0)
		public double getAdminFee()
			{
				return this.adminFee;
			}
			
		public void setAdminFee(double adminFee)
			{
				this.adminFee = adminFee;
			}
			
		@Column(name = "AdminFeePercentage", precision = 53, scale = 0)
		public Double getAdminFeePercentage()
			{
				return this.adminFeePercentage;
			}
			
		public void setAdminFeePercentage(Double adminFeePercentage)
			{
				this.adminFeePercentage = adminFeePercentage;
			}
			
		@Column(name = "AddAdminFee", nullable = false, precision = 53, scale = 0)
		public double getAddAdminFee()
			{
				return this.addAdminFee;
			}
			
		public void setAddAdminFee(double addAdminFee)
			{
				this.addAdminFee = addAdminFee;
			}
			
		@Column(name = "FiduciaFee", nullable = false, precision = 53, scale = 0)
		public double getFiduciaFee()
			{
				return this.fiduciaFee;
			}
			
		public void setFiduciaFee(double fiduciaFee)
			{
				this.fiduciaFee = fiduciaFee;
			}
			
		@Column(name = "ProvisionFee", nullable = false, precision = 53, scale = 0)
		public double getProvisionFee()
			{
				return this.provisionFee;
			}
			
		public void setProvisionFee(double provisionFee)
			{
				this.provisionFee = provisionFee;
			}
			
		@Column(name = "NotaryFee", nullable = false, precision = 53, scale = 0)
		public double getNotaryFee()
			{
				return this.notaryFee;
			}
			
		public void setNotaryFee(double notaryFee)
			{
				this.notaryFee = notaryFee;
			}
			
		@Column(name = "SurveyFee", nullable = false, precision = 53, scale = 0)
		public double getSurveyFee()
			{
				return this.surveyFee;
			}
			
		public void setSurveyFee(double surveyFee)
			{
				this.surveyFee = surveyFee;
			}
			
		@Column(name = "OtherFee", nullable = false, precision = 53, scale = 0)
		public double getOtherFee()
			{
				return this.otherFee;
			}
			
		public void setOtherFee(double otherFee)
			{
				this.otherFee = otherFee;
			}
			
		@Column(name = "CrossDefaultApplicationId", length = 20)
		public String getCrossDefaultApplicationId()
			{
				return this.crossDefaultApplicationId;
			}
			
		public void setCrossDefaultApplicationId(String crossDefaultApplicationId)
			{
				this.crossDefaultApplicationId = crossDefaultApplicationId;
			}
			
		@Column(name = "Notes", length = 8000)
		public String getNotes()
			{
				return this.notes;
			}
			
		public void setNotes(String notes)
			{
				this.notes = notes;
			}
			
		@Column(name = "DiffRateAmount", nullable = false, precision = 53, scale = 0)
		public double getDiffRateAmount()
			{
				return this.diffRateAmount;
			}
			
		public void setDiffRateAmount(double diffRateAmount)
			{
				this.diffRateAmount = diffRateAmount;
			}
			
		@Column(name = "DiffRateStdAmount", nullable = false, precision = 53, scale = 0)
		public double getDiffRateStdAmount()
			{
				return this.diffRateStdAmount;
			}
			
		public void setDiffRateStdAmount(double diffRateStdAmount)
			{
				this.diffRateStdAmount = diffRateStdAmount;
			}
			
		@Column(name = "CreditScore", nullable = false, precision = 53, scale = 0)
		public double getCreditScore()
			{
				return this.creditScore;
			}
			
		public void setCreditScore(double creditScore)
			{
				this.creditScore = creditScore;
			}
			
		@Column(name = "CreditScoringResult", length = 1)
		public String getCreditScoringResult()
			{
				return this.creditScoringResult;
			}
			
		public void setCreditScoringResult(String creditScoringResult)
			{
				this.creditScoringResult = creditScoringResult;
			}
			
		@Column(name = "FinanceType", nullable = false, length = 2)
		public String getFinanceType()
			{
				return this.financeType;
			}
			
		public void setFinanceType(String financeType)
			{
				this.financeType = financeType;
			}
			
		@Column(name = "ProductType", nullable = false, length = 2)
		public String getProductType()
			{
				return this.productType;
			}
			
		public void setProductType(String productType)
			{
				this.productType = productType;
			}
			
		@Column(name = "ContractStatus", nullable = false, length = 3)
		public String getContractStatus()
			{
				return this.contractStatus;
			}
			
		public void setContractStatus(String contractStatus)
			{
				this.contractStatus = contractStatus;
			}
			
		@Column(name = "DefaultStatus", nullable = false, length = 3)
		public String getDefaultStatus()
			{
				return this.defaultStatus;
			}
			
		public void setDefaultStatus(String defaultStatus)
			{
				this.defaultStatus = defaultStatus;
			}
			
		@Column(name = "ApplicationStep", nullable = false, length = 3)
		public String getApplicationStep()
			{
				return this.applicationStep;
			}
			
		public void setApplicationStep(String applicationStep)
			{
				this.applicationStep = applicationStep;
			}
			
		@Column(name = "OSP", nullable = false, precision = 53, scale = 0)
		public double getOsp()
			{
				return this.osp;
			}
			
		public void setOsp(double osp)
			{
				this.osp = osp;
			}
			
		@Column(name = "OSI", nullable = false, precision = 53, scale = 0)
		public double getOsi()
			{
				return this.osi;
			}
			
		public void setOsi(double osi)
			{
				this.osi = osi;
			}
			
		@Column(name = "OSPUndue", nullable = false, precision = 53, scale = 0)
		public double getOspundue()
			{
				return this.ospundue;
			}
			
		public void setOspundue(double ospundue)
			{
				this.ospundue = ospundue;
			}
			
		@Column(name = "OSIUndue", nullable = false, precision = 53, scale = 0)
		public double getOsiundue()
			{
				return this.osiundue;
			}
			
		public void setOsiundue(double osiundue)
			{
				this.osiundue = osiundue;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NextInstDate", length = 23)
		public Date getNextInstDate()
			{
				return this.nextInstDate;
			}
			
		public void setNextInstDate(Date nextInstDate)
			{
				this.nextInstDate = nextInstDate;
			}
			
		@Column(name = "NextInstNumber", nullable = false)
		public short getNextInstNumber()
			{
				return this.nextInstNumber;
			}
			
		public void setNextInstNumber(short nextInstNumber)
			{
				this.nextInstNumber = nextInstNumber;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NextInstDueDate", length = 23)
		public Date getNextInstDueDate()
			{
				return this.nextInstDueDate;
			}
			
		public void setNextInstDueDate(Date nextInstDueDate)
			{
				this.nextInstDueDate = nextInstDueDate;
			}
			
		@Column(name = "NextInstDueNumber", nullable = false)
		public short getNextInstDueNumber()
			{
				return this.nextInstDueNumber;
			}
			
		public void setNextInstDueNumber(short nextInstDueNumber)
			{
				this.nextInstDueNumber = nextInstDueNumber;
			}
			
		@Column(name = "TDPAmount", nullable = false, precision = 53, scale = 0)
		public double getTdpamount()
			{
				return this.tdpamount;
			}
			
		public void setTdpamount(double tdpamount)
			{
				this.tdpamount = tdpamount;
			}
			
		@Column(name = "PrepaidAmt", precision = 53, scale = 0)
		public Double getPrepaidAmt()
			{
				return this.prepaidAmt;
			}
			
		public void setPrepaidAmt(Double prepaidAmt)
			{
				this.prepaidAmt = prepaidAmt;
			}
			
		@Column(name = "IsSyariah")
		public Short getIsSyariah()
			{
				return this.isSyariah;
			}
			
		public void setIsSyariah(Short isSyariah)
			{
				this.isSyariah = isSyariah;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<GoLive> getGoLives()
			{
				return this.goLives;
			}
			
		public void setGoLives(Set<GoLive> goLives)
			{
				this.goLives = goLives;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntMnt> getAgrmntMnts()
			{
				return this.agrmntMnts;
			}
			
		public void setAgrmntMnts(Set<AgrmntMnt> agrmntMnts)
			{
				this.agrmntMnts = agrmntMnts;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntFund> getAgrmntFunds()
			{
				return this.agrmntFunds;
			}
			
		public void setAgrmntFunds(Set<AgrmntFund> agrmntFunds)
			{
				this.agrmntFunds = agrmntFunds;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<InstSchedule> getInstSchedules()
			{
				return this.instSchedules;
			}
			
		public void setInstSchedules(Set<InstSchedule> instSchedules)
			{
				this.instSchedules = instSchedules;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntColl> getAgrmntColls()
			{
				return this.agrmntColls;
			}
			
		public void setAgrmntColls(Set<AgrmntColl> agrmntColls)
			{
				this.agrmntColls = agrmntColls;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntAsset> getAgrmntAssets()
			{
				return this.agrmntAssets;
			}
			
		public void setAgrmntAssets(Set<AgrmntAsset> agrmntAssets)
			{
				this.agrmntAssets = agrmntAssets;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntBankStatementInfo> getAgrmntBankStatementInfos()
			{
				return this.agrmntBankStatementInfos;
			}
			
		public void setAgrmntBankStatementInfos(Set<AgrmntBankStatementInfo> agrmntBankStatementInfos)
			{
				this.agrmntBankStatementInfos = agrmntBankStatementInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntReffInfo> getAgrmntReffInfos()
			{
				return this.agrmntReffInfos;
			}
			
		public void setAgrmntReffInfos(Set<AgrmntReffInfo> agrmntReffInfos)
			{
				this.agrmntReffInfos = agrmntReffInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PayHistHdr> getPayHistHdrs()
			{
				return this.payHistHdrs;
			}
			
		public void setPayHistHdrs(Set<PayHistHdr> payHistHdrs)
			{
				this.payHistHdrs = payHistHdrs;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<PaymentReceive> getPaymentReceives()
			{
				return this.paymentReceives;
			}
			
		public void setPaymentReceives(Set<PaymentReceive> paymentReceives)
			{
				this.paymentReceives = paymentReceives;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntEmployee> getAgrmntEmployees()
			{
				return this.agrmntEmployees;
			}
			
		public void setAgrmntEmployees(Set<AgrmntEmployee> agrmntEmployees)
			{
				this.agrmntEmployees = agrmntEmployees;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntIns> getAgrmntInses()
			{
				return this.agrmntInses;
			}
			
		public void setAgrmntInses(Set<AgrmntIns> agrmntInses)
			{
				this.agrmntInses = agrmntInses;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntBankStatementInfo> getAgrmntBankStatementInfos_1()
			{
				return this.agrmntBankStatementInfos_1;
			}
			
		public void setAgrmntBankStatementInfos_1(Set<AgrmntBankStatementInfo> agrmntBankStatementInfos_1)
			{
				this.agrmntBankStatementInfos_1 = agrmntBankStatementInfos_1;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntEmployeeInfo> getAgrmntEmployeeInfos()
			{
				return this.agrmntEmployeeInfos;
			}
			
		public void setAgrmntEmployeeInfos(Set<AgrmntEmployeeInfo> agrmntEmployeeInfos)
			{
				this.agrmntEmployeeInfos = agrmntEmployeeInfos;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "agrmnt")
		public Set<AgrmntMailingInfo> getAgrmntMailingInfos()
			{
				return this.agrmntMailingInfos;
			}
			
		public void setAgrmntMailingInfos(Set<AgrmntMailingInfo> agrmntMailingInfos)
			{
				this.agrmntMailingInfos = agrmntMailingInfos;
			}
			
	}
