
package com.adibrata.smartdealer.model;
// Generated Sep 3, 2015 3:54:52 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AgrmntSupplier generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "AgrmntSupplier", catalog = "SmartDealer")
public class AgrmntSupplier implements java.io.Serializable
	{
		
		private long id;
		private AgrmntAsset agrmntAsset;
		private Long supplierId;
		private Short seqNo;
		private Double otrAmount;
		private Double dpamount;
		private String notes;
		
		public AgrmntSupplier()
			{
			}
			
		public AgrmntSupplier(long id)
			{
				this.id = id;
			}
			
		public AgrmntSupplier(long id, AgrmntAsset agrmntAsset, Long supplierId, Short seqNo, Double otrAmount, Double dpamount, String notes)
			{
				this.id = id;
				this.agrmntAsset = agrmntAsset;
				this.supplierId = supplierId;
				this.seqNo = seqNo;
				this.otrAmount = otrAmount;
				this.dpamount = dpamount;
				this.notes = notes;
			}
			
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "AgrmntAssetId")
		public AgrmntAsset getAgrmntAsset()
			{
				return this.agrmntAsset;
			}
			
		public void setAgrmntAsset(AgrmntAsset agrmntAsset)
			{
				this.agrmntAsset = agrmntAsset;
			}
			
		@Column(name = "SupplierId")
		public Long getSupplierId()
			{
				return this.supplierId;
			}
			
		public void setSupplierId(Long supplierId)
			{
				this.supplierId = supplierId;
			}
			
		@Column(name = "SeqNo")
		public Short getSeqNo()
			{
				return this.seqNo;
			}
			
		public void setSeqNo(Short seqNo)
			{
				this.seqNo = seqNo;
			}
			
		@Column(name = "OtrAmount", precision = 53, scale = 0)
		public Double getOtrAmount()
			{
				return this.otrAmount;
			}
			
		public void setOtrAmount(Double otrAmount)
			{
				this.otrAmount = otrAmount;
			}
			
		@Column(name = "DPAmount", precision = 53, scale = 0)
		public Double getDpamount()
			{
				return this.dpamount;
			}
			
		public void setDpamount(Double dpamount)
			{
				this.dpamount = dpamount;
			}
			
		@Column(name = "Notes", length = 8000)
		public String getNotes()
			{
				return this.notes;
			}
			
		public void setNotes(String notes)
			{
				this.notes = notes;
			}
			
	}
