
package com.adibrata.smartdealer.model;
// Generated Jul 21, 2015 2:35:33 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.Table;

/**
 * AgrmntEmployee generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "AgrmntEmployee", catalog = "SmartDealer")
public class AgrmntEmployee implements java.io.Serializable
	{
		
		private AgrmntEmployeeId id;
		
		public AgrmntEmployee()
			{
			}
			
		public AgrmntEmployee(AgrmntEmployeeId id)
			{
				this.id = id;
			}
			
		@EmbeddedId
		
		@AttributeOverrides(
			{
			        @AttributeOverride(name = "id", column = @Column(name = "Id") ), @AttributeOverride(name = "agrmntId", column = @Column(name = "AgrmntId") ), @AttributeOverride(name = "aoid", column = @Column(name = "AOID") ),
			        @AttributeOverride(name = "caid", column = @Column(name = "CAID") ), @AttributeOverride(name = "salesmanId", column = @Column(name = "SalesmanID") ),
			        @AttributeOverride(name = "salesSupervisorId", column = @Column(name = "SalesSupervisorID") ), @AttributeOverride(name = "supplierAdminId", column = @Column(name = "SupplierAdminID") ),
			        @AttributeOverride(name = "dtmUpd", column = @Column(name = "DtmUpd", length = 16) ), @AttributeOverride(name = "usrUpd", column = @Column(name = "UsrUpd", length = 50) ),
			        @AttributeOverride(name = "dtmCrt", column = @Column(name = "DtmCrt", length = 16) ), @AttributeOverride(name = "usrCrt", column = @Column(name = "UsrCrt", length = 50) )
			})
		public AgrmntEmployeeId getId()
			{
				return this.id;
			}
			
		public void setId(AgrmntEmployeeId id)
			{
				this.id = id;
			}
			
	}
