
package com.adibrata.smartdealer.model;
// Generated Aug 23, 2015 12:40:11 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Application generated by hbm2java
 */
@Entity
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "Application", catalog = "SmartDealer")
public class Application implements java.io.Serializable
	{
		
		/**
		*
		*/
		private static final long serialVersionUID = 1L;
		
		private long id;
		private String partnerCode;
		private Long officeId;
		private Long customerId;
		private String appCode;
		private String usrCrt;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private Set<Agrmnt> agrmnts = new HashSet<Agrmnt>(0);
		
		public Application()
			{
			}
			
		public Application(final long id)
			{
				this.id = id;
			}
			
		public Application(final long id, final String partnerCode, final Long officeId, final Long customerId, final String appCode, final String usrCrt, final Date dtmUpd, final String usrUpd, final Date dtmCrt, final Set<Agrmnt> agrmnts)
			{
				this.id = id;
				this.partnerCode = partnerCode;
				this.officeId = officeId;
				this.customerId = customerId;
				this.appCode = appCode;
				this.usrCrt = usrCrt;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.agrmnts = agrmnts;
			}
			
		@Id
		@GeneratedValue(strategy = GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(final long id)
			{
				this.id = id;
			}
			
		@Column(name = "PartnerCode", length = 20)
		public String getPartnerCode()
			{
				return this.partnerCode;
			}
			
		public void setPartnerCode(final String partnerCode)
			{
				this.partnerCode = partnerCode;
			}
			
		@Column(name = "OfficeId")
		public Long getOfficeId()
			{
				return this.officeId;
			}
			
		public void setOfficeId(final Long officeId)
			{
				this.officeId = officeId;
			}
			
		@Column(name = "CustomerId")
		public Long getCustomerId()
			{
				return this.customerId;
			}
			
		public void setCustomerId(final Long customerId)
			{
				this.customerId = customerId;
			}
			
		@Column(name = "AppCode", length = 20)
		public String getAppCode()
			{
				return this.appCode;
			}
			
		public void setAppCode(final String appCode)
			{
				this.appCode = appCode;
			}
			
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(final String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(final Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(final String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(final Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "application")
		public Set<Agrmnt> getAgrmnts()
			{
				return this.agrmnts;
			}
			
		public void setAgrmnts(final Set<Agrmnt> agrmnts)
			{
				this.agrmnts = agrmnts;
			}
			
	}
