
package com.adibrata.smartdealer.model;
// Generated Sep 27, 2015 10:48:45 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InsRateFromInsco generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "InsRateFromInsco", catalog = "SmartDealer")
public class InsRateFromInsco implements java.io.Serializable
	{
		
		private long id;
		private InsCoBranch insCoBranch;
		private String insTypeCode;
		private String usageCode;
		private Short newUsed;
		private Long currencyId;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private String usrCrt;
		private Set<InsRateFromInscoDtl> insRateFromInscoDtls = new HashSet<InsRateFromInscoDtl>(0);
		
		public InsRateFromInsco()
			{
			}
			
		public InsRateFromInsco(long id)
			{
				this.id = id;
			}
			
		public InsRateFromInsco(long id, InsCoBranch insCoBranch, String insTypeCode, String usageCode, Short newUsed, Long currencyId, Date dtmUpd, String usrUpd, Date dtmCrt, String usrCrt, Set<InsRateFromInscoDtl> insRateFromInscoDtls)
			{
				this.id = id;
				this.insCoBranch = insCoBranch;
				this.insTypeCode = insTypeCode;
				this.usageCode = usageCode;
				this.newUsed = newUsed;
				this.currencyId = currencyId;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.usrCrt = usrCrt;
				this.insRateFromInscoDtls = insRateFromInscoDtls;
			}
			
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "InsCompanyOfficeId")
		public InsCoBranch getInsCoBranch()
			{
				return this.insCoBranch;
			}
			
		public void setInsCoBranch(InsCoBranch insCoBranch)
			{
				this.insCoBranch = insCoBranch;
			}
			
		@Column(name = "InsTypeCode", length = 20)
		public String getInsTypeCode()
			{
				return this.insTypeCode;
			}
			
		public void setInsTypeCode(String insTypeCode)
			{
				this.insTypeCode = insTypeCode;
			}
			
		@Column(name = "UsageCode", length = 20)
		public String getUsageCode()
			{
				return this.usageCode;
			}
			
		public void setUsageCode(String usageCode)
			{
				this.usageCode = usageCode;
			}
			
		@Column(name = "NewUsed")
		public Short getNewUsed()
			{
				return this.newUsed;
			}
			
		public void setNewUsed(Short newUsed)
			{
				this.newUsed = newUsed;
			}
			
		@Column(name = "CurrencyId")
		public Long getCurrencyId()
			{
				return this.currencyId;
			}
			
		public void setCurrencyId(Long currencyId)
			{
				this.currencyId = currencyId;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 23)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd")
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 23)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
		@Column(name = "UsrCrt")
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "insRateFromInsco")
		public Set<InsRateFromInscoDtl> getInsRateFromInscoDtls()
			{
				return this.insRateFromInscoDtls;
			}
			
		public void setInsRateFromInscoDtls(Set<InsRateFromInscoDtl> insRateFromInscoDtls)
			{
				this.insRateFromInscoDtls = insRateFromInscoDtls;
			}
			
	}
