
package com.adibrata.smartdealer.model;
// Generated Sep 10, 2015 12:03:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InsRateToCustDtl generated by hbm2java
 */
@Entity
@Table(name = "InsRateToCustDtl", catalog = "SmartDealer")
public class InsRateToCustDtl implements java.io.Serializable
	{
		
		private long id;
		private InsRateToCust insRateToCust;
		private String coverTypeCode;
		private Short yearNum;
		private double rateForGroup;
		private double rateForNonGroup;
		private double rateForRo;
		private double srccrate;
		private double floodRate;
		private double sumInsured;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private String usrCrt;
		
		public InsRateToCustDtl()
			{
			}
			
		public InsRateToCustDtl(long id, double rateForGroup, double rateForNonGroup, double rateForRo, double srccrate, double floodRate, double sumInsured)
			{
				this.id = id;
				this.rateForGroup = rateForGroup;
				this.rateForNonGroup = rateForNonGroup;
				this.rateForRo = rateForRo;
				this.srccrate = srccrate;
				this.floodRate = floodRate;
				this.sumInsured = sumInsured;
			}
			
		public InsRateToCustDtl(long id, InsRateToCust insRateToCust, String coverTypeCode, Short yearNum, double rateForGroup, double rateForNonGroup, double rateForRo, double srccrate, double floodRate, double sumInsured, Date dtmUpd,
		        String usrUpd, Date dtmCrt, String usrCrt)
			{
				this.id = id;
				this.insRateToCust = insRateToCust;
				this.coverTypeCode = coverTypeCode;
				this.yearNum = yearNum;
				this.rateForGroup = rateForGroup;
				this.rateForNonGroup = rateForNonGroup;
				this.rateForRo = rateForRo;
				this.srccrate = srccrate;
				this.floodRate = floodRate;
				this.sumInsured = sumInsured;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.usrCrt = usrCrt;
			}
			
		@Id
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "InsRateToCustID")
		public InsRateToCust getInsRateToCust()
			{
				return this.insRateToCust;
			}
			
		public void setInsRateToCust(InsRateToCust insRateToCust)
			{
				this.insRateToCust = insRateToCust;
			}
			
		@Column(name = "CoverTypeCode", length = 20)
		public String getCoverTypeCode()
			{
				return this.coverTypeCode;
			}
			
		public void setCoverTypeCode(String coverTypeCode)
			{
				this.coverTypeCode = coverTypeCode;
			}
			
		@Column(name = "YearNum")
		public Short getYearNum()
			{
				return this.yearNum;
			}
			
		public void setYearNum(Short yearNum)
			{
				this.yearNum = yearNum;
			}
			
		@Column(name = "RateForGroup", nullable = false, precision = 53, scale = 0)
		public double getRateForGroup()
			{
				return this.rateForGroup;
			}
			
		public void setRateForGroup(double rateForGroup)
			{
				this.rateForGroup = rateForGroup;
			}
			
		@Column(name = "RateForNonGroup", nullable = false, precision = 53, scale = 0)
		public double getRateForNonGroup()
			{
				return this.rateForNonGroup;
			}
			
		public void setRateForNonGroup(double rateForNonGroup)
			{
				this.rateForNonGroup = rateForNonGroup;
			}
			
		@Column(name = "RateForRO", nullable = false, precision = 53, scale = 0)
		public double getRateForRo()
			{
				return this.rateForRo;
			}
			
		public void setRateForRo(double rateForRo)
			{
				this.rateForRo = rateForRo;
			}
			
		@Column(name = "SRCCRate", nullable = false, precision = 53, scale = 0)
		public double getSrccrate()
			{
				return this.srccrate;
			}
			
		public void setSrccrate(double srccrate)
			{
				this.srccrate = srccrate;
			}
			
		@Column(name = "FloodRate", nullable = false, precision = 53, scale = 0)
		public double getFloodRate()
			{
				return this.floodRate;
			}
			
		public void setFloodRate(double floodRate)
			{
				this.floodRate = floodRate;
			}
			
		@Column(name = "SumInsured", nullable = false, precision = 53, scale = 0)
		public double getSumInsured()
			{
				return this.sumInsured;
			}
			
		public void setSumInsured(double sumInsured)
			{
				this.sumInsured = sumInsured;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 23)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd")
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 23)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
		@Column(name = "UsrCrt")
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
	}
