
package com.adibrata.smartdealer.model;
// Generated Aug 31, 2015 2:44:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity; import org.hibernate.annotations.Cache; import org.hibernate.annotations.CacheConcurrencyStrategy; import javax.persistence.Cacheable;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NegCust generated by hbm2java
 */
@Entity @Cacheable @Cache(usage = CacheConcurrencyStrategy.TRANSACTIONAL)
@Table(name = "NegCust", catalog = "SmartDealer")
public class NegCust implements java.io.Serializable
	{
		
		private long id;
		private Customer customer;
		private String name;
		private String idtype;
		private String idnumber;
		private String idnumberChecking;
		private String birthPlace;
		private Date birthDate;
		private String legalAddress;
		private String legalRt;
		private String legalRw;
		private String legalKelurahan;
		private String legalKecamatan;
		private String legalCity;
		private String legalZipCode;
		private String legalAreaPhone1;
		private String legalPhone1;
		private String legalAreaPhone2;
		private String legalPhone2;
		private String legalAreaFax;
		private String legalFax;
		private String mobilePhone;
		private String email;
		private String badType;
		private String dataSource;
		private String notes;
		private short isActive;
		private Date nonActiveDate;
		private short numOfSkt;
		private short numOfRejectAfterSurvey;
		private Short numOfRejectedApplication;
		private Date lastRejectedApplicationDate;
		private Short numAgreementOvd;
		private Date lastAgreementOvddate;
		private Short numOfPdcbounce;
		private Date lastPdcbounceDate;
		private Short numOfInventory;
		private Date lastInventoryDate;
		private Short numOfWriteOff;
		private Date lastWriteOffDate;
		private String familyMemberOf;
		private Date badDebtDate;
		private String rejectionReasonAfterId;
		private Date lastRejectionAfterDate;
		private Date lastSktdate;
		private String biologicalMothersName;
		private String usrCrt;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		
		public NegCust()
			{
			}
			
		public NegCust(long id, String name, String notes, short isActive, short numOfSkt, short numOfRejectAfterSurvey)
			{
				this.id = id;
				this.name = name;
				this.notes = notes;
				this.isActive = isActive;
				this.numOfSkt = numOfSkt;
				this.numOfRejectAfterSurvey = numOfRejectAfterSurvey;
			}
			
		public NegCust(long id, Customer customer, String name, String idtype, String idnumber, String idnumberChecking, String birthPlace, Date birthDate, String legalAddress, String legalRt, String legalRw, String legalKelurahan,
		        String legalKecamatan, String legalCity, String legalZipCode, String legalAreaPhone1, String legalPhone1, String legalAreaPhone2, String legalPhone2, String legalAreaFax, String legalFax, String mobilePhone, String email,
		        String badType, String dataSource, String notes, short isActive, Date nonActiveDate, short numOfSkt, short numOfRejectAfterSurvey, Short numOfRejectedApplication, Date lastRejectedApplicationDate, Short numAgreementOvd,
		        Date lastAgreementOvddate, Short numOfPdcbounce, Date lastPdcbounceDate, Short numOfInventory, Date lastInventoryDate, Short numOfWriteOff, Date lastWriteOffDate, String familyMemberOf, Date badDebtDate, String rejectionReasonAfterId,
		        Date lastRejectionAfterDate, Date lastSktdate, String biologicalMothersName, String usrCrt, Date dtmUpd, String usrUpd, Date dtmCrt)
			{
				this.id = id;
				this.customer = customer;
				this.name = name;
				this.idtype = idtype;
				this.idnumber = idnumber;
				this.idnumberChecking = idnumberChecking;
				this.birthPlace = birthPlace;
				this.birthDate = birthDate;
				this.legalAddress = legalAddress;
				this.legalRt = legalRt;
				this.legalRw = legalRw;
				this.legalKelurahan = legalKelurahan;
				this.legalKecamatan = legalKecamatan;
				this.legalCity = legalCity;
				this.legalZipCode = legalZipCode;
				this.legalAreaPhone1 = legalAreaPhone1;
				this.legalPhone1 = legalPhone1;
				this.legalAreaPhone2 = legalAreaPhone2;
				this.legalPhone2 = legalPhone2;
				this.legalAreaFax = legalAreaFax;
				this.legalFax = legalFax;
				this.mobilePhone = mobilePhone;
				this.email = email;
				this.badType = badType;
				this.dataSource = dataSource;
				this.notes = notes;
				this.isActive = isActive;
				this.nonActiveDate = nonActiveDate;
				this.numOfSkt = numOfSkt;
				this.numOfRejectAfterSurvey = numOfRejectAfterSurvey;
				this.numOfRejectedApplication = numOfRejectedApplication;
				this.lastRejectedApplicationDate = lastRejectedApplicationDate;
				this.numAgreementOvd = numAgreementOvd;
				this.lastAgreementOvddate = lastAgreementOvddate;
				this.numOfPdcbounce = numOfPdcbounce;
				this.lastPdcbounceDate = lastPdcbounceDate;
				this.numOfInventory = numOfInventory;
				this.lastInventoryDate = lastInventoryDate;
				this.numOfWriteOff = numOfWriteOff;
				this.lastWriteOffDate = lastWriteOffDate;
				this.familyMemberOf = familyMemberOf;
				this.badDebtDate = badDebtDate;
				this.rejectionReasonAfterId = rejectionReasonAfterId;
				this.lastRejectionAfterDate = lastRejectionAfterDate;
				this.lastSktdate = lastSktdate;
				this.biologicalMothersName = biologicalMothersName;
				this.usrCrt = usrCrt;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
			}
			
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		
		@Column(name = "Id", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
			
		public void setId(long id)
			{
				this.id = id;
			}
			
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "CustomerId")
		public Customer getCustomer()
			{
				return this.customer;
			}
			
		public void setCustomer(Customer customer)
			{
				this.customer = customer;
			}
			
		@Column(name = "Name", nullable = false, length = 50)
		public String getName()
			{
				return this.name;
			}
			
		public void setName(String name)
			{
				this.name = name;
			}
			
		@Column(name = "IDType", length = 10)
		public String getIdtype()
			{
				return this.idtype;
			}
			
		public void setIdtype(String idtype)
			{
				this.idtype = idtype;
			}
			
		@Column(name = "IDNumber", length = 40)
		public String getIdnumber()
			{
				return this.idnumber;
			}
			
		public void setIdnumber(String idnumber)
			{
				this.idnumber = idnumber;
			}
			
		@Column(name = "IDNumberChecking", length = 40)
		public String getIdnumberChecking()
			{
				return this.idnumberChecking;
			}
			
		public void setIdnumberChecking(String idnumberChecking)
			{
				this.idnumberChecking = idnumberChecking;
			}
			
		@Column(name = "BirthPlace", length = 20)
		public String getBirthPlace()
			{
				return this.birthPlace;
			}
			
		public void setBirthPlace(String birthPlace)
			{
				this.birthPlace = birthPlace;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "BirthDate", length = 23)
		public Date getBirthDate()
			{
				return this.birthDate;
			}
			
		public void setBirthDate(Date birthDate)
			{
				this.birthDate = birthDate;
			}
			
		@Column(name = "LegalAddress", length = 100)
		public String getLegalAddress()
			{
				return this.legalAddress;
			}
			
		public void setLegalAddress(String legalAddress)
			{
				this.legalAddress = legalAddress;
			}
			
		@Column(name = "LegalRT", length = 3)
		public String getLegalRt()
			{
				return this.legalRt;
			}
			
		public void setLegalRt(String legalRt)
			{
				this.legalRt = legalRt;
			}
			
		@Column(name = "LegalRW", length = 3)
		public String getLegalRw()
			{
				return this.legalRw;
			}
			
		public void setLegalRw(String legalRw)
			{
				this.legalRw = legalRw;
			}
			
		@Column(name = "LegalKelurahan", length = 30)
		public String getLegalKelurahan()
			{
				return this.legalKelurahan;
			}
			
		public void setLegalKelurahan(String legalKelurahan)
			{
				this.legalKelurahan = legalKelurahan;
			}
			
		@Column(name = "LegalKecamatan", length = 30)
		public String getLegalKecamatan()
			{
				return this.legalKecamatan;
			}
			
		public void setLegalKecamatan(String legalKecamatan)
			{
				this.legalKecamatan = legalKecamatan;
			}
			
		@Column(name = "LegalCity", length = 30)
		public String getLegalCity()
			{
				return this.legalCity;
			}
			
		public void setLegalCity(String legalCity)
			{
				this.legalCity = legalCity;
			}
			
		@Column(name = "LegalZipCode", length = 5)
		public String getLegalZipCode()
			{
				return this.legalZipCode;
			}
			
		public void setLegalZipCode(String legalZipCode)
			{
				this.legalZipCode = legalZipCode;
			}
			
		@Column(name = "LegalAreaPhone1", length = 4)
		public String getLegalAreaPhone1()
			{
				return this.legalAreaPhone1;
			}
			
		public void setLegalAreaPhone1(String legalAreaPhone1)
			{
				this.legalAreaPhone1 = legalAreaPhone1;
			}
			
		@Column(name = "LegalPhone1", length = 15)
		public String getLegalPhone1()
			{
				return this.legalPhone1;
			}
			
		public void setLegalPhone1(String legalPhone1)
			{
				this.legalPhone1 = legalPhone1;
			}
			
		@Column(name = "LegalAreaPhone2", length = 4)
		public String getLegalAreaPhone2()
			{
				return this.legalAreaPhone2;
			}
			
		public void setLegalAreaPhone2(String legalAreaPhone2)
			{
				this.legalAreaPhone2 = legalAreaPhone2;
			}
			
		@Column(name = "LegalPhone2", length = 15)
		public String getLegalPhone2()
			{
				return this.legalPhone2;
			}
			
		public void setLegalPhone2(String legalPhone2)
			{
				this.legalPhone2 = legalPhone2;
			}
			
		@Column(name = "LegalAreaFax", length = 4)
		public String getLegalAreaFax()
			{
				return this.legalAreaFax;
			}
			
		public void setLegalAreaFax(String legalAreaFax)
			{
				this.legalAreaFax = legalAreaFax;
			}
			
		@Column(name = "LegalFax", length = 15)
		public String getLegalFax()
			{
				return this.legalFax;
			}
			
		public void setLegalFax(String legalFax)
			{
				this.legalFax = legalFax;
			}
			
		@Column(name = "MobilePhone", length = 20)
		public String getMobilePhone()
			{
				return this.mobilePhone;
			}
			
		public void setMobilePhone(String mobilePhone)
			{
				this.mobilePhone = mobilePhone;
			}
			
		@Column(name = "Email", length = 50)
		public String getEmail()
			{
				return this.email;
			}
			
		public void setEmail(String email)
			{
				this.email = email;
			}
			
		@Column(name = "BadType", length = 1)
		public String getBadType()
			{
				return this.badType;
			}
			
		public void setBadType(String badType)
			{
				this.badType = badType;
			}
			
		@Column(name = "DataSource", length = 100)
		public String getDataSource()
			{
				return this.dataSource;
			}
			
		public void setDataSource(String dataSource)
			{
				this.dataSource = dataSource;
			}
			
		@Column(name = "Notes", nullable = false, length = 8000)
		public String getNotes()
			{
				return this.notes;
			}
			
		public void setNotes(String notes)
			{
				this.notes = notes;
			}
			
		@Column(name = "IsActive", nullable = false)
		public short getIsActive()
			{
				return this.isActive;
			}
			
		public void setIsActive(short isActive)
			{
				this.isActive = isActive;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "NonActiveDate", length = 23)
		public Date getNonActiveDate()
			{
				return this.nonActiveDate;
			}
			
		public void setNonActiveDate(Date nonActiveDate)
			{
				this.nonActiveDate = nonActiveDate;
			}
			
		@Column(name = "NumOfSKT", nullable = false)
		public short getNumOfSkt()
			{
				return this.numOfSkt;
			}
			
		public void setNumOfSkt(short numOfSkt)
			{
				this.numOfSkt = numOfSkt;
			}
			
		@Column(name = "NumOfRejectAfterSurvey", nullable = false)
		public short getNumOfRejectAfterSurvey()
			{
				return this.numOfRejectAfterSurvey;
			}
			
		public void setNumOfRejectAfterSurvey(short numOfRejectAfterSurvey)
			{
				this.numOfRejectAfterSurvey = numOfRejectAfterSurvey;
			}
			
		@Column(name = "NumOfRejectedApplication")
		public Short getNumOfRejectedApplication()
			{
				return this.numOfRejectedApplication;
			}
			
		public void setNumOfRejectedApplication(Short numOfRejectedApplication)
			{
				this.numOfRejectedApplication = numOfRejectedApplication;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastRejectedApplicationDate", length = 23)
		public Date getLastRejectedApplicationDate()
			{
				return this.lastRejectedApplicationDate;
			}
			
		public void setLastRejectedApplicationDate(Date lastRejectedApplicationDate)
			{
				this.lastRejectedApplicationDate = lastRejectedApplicationDate;
			}
			
		@Column(name = "NumAgreementOVD")
		public Short getNumAgreementOvd()
			{
				return this.numAgreementOvd;
			}
			
		public void setNumAgreementOvd(Short numAgreementOvd)
			{
				this.numAgreementOvd = numAgreementOvd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastAgreementOVDDate", length = 23)
		public Date getLastAgreementOvddate()
			{
				return this.lastAgreementOvddate;
			}
			
		public void setLastAgreementOvddate(Date lastAgreementOvddate)
			{
				this.lastAgreementOvddate = lastAgreementOvddate;
			}
			
		@Column(name = "NumOfPDCBounce")
		public Short getNumOfPdcbounce()
			{
				return this.numOfPdcbounce;
			}
			
		public void setNumOfPdcbounce(Short numOfPdcbounce)
			{
				this.numOfPdcbounce = numOfPdcbounce;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastPDCBounceDate", length = 23)
		public Date getLastPdcbounceDate()
			{
				return this.lastPdcbounceDate;
			}
			
		public void setLastPdcbounceDate(Date lastPdcbounceDate)
			{
				this.lastPdcbounceDate = lastPdcbounceDate;
			}
			
		@Column(name = "NumOfInventory")
		public Short getNumOfInventory()
			{
				return this.numOfInventory;
			}
			
		public void setNumOfInventory(Short numOfInventory)
			{
				this.numOfInventory = numOfInventory;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastInventoryDate", length = 23)
		public Date getLastInventoryDate()
			{
				return this.lastInventoryDate;
			}
			
		public void setLastInventoryDate(Date lastInventoryDate)
			{
				this.lastInventoryDate = lastInventoryDate;
			}
			
		@Column(name = "NumOfWriteOff")
		public Short getNumOfWriteOff()
			{
				return this.numOfWriteOff;
			}
			
		public void setNumOfWriteOff(Short numOfWriteOff)
			{
				this.numOfWriteOff = numOfWriteOff;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastWriteOffDate", length = 23)
		public Date getLastWriteOffDate()
			{
				return this.lastWriteOffDate;
			}
			
		public void setLastWriteOffDate(Date lastWriteOffDate)
			{
				this.lastWriteOffDate = lastWriteOffDate;
			}
			
		@Column(name = "FamilyMemberOf", length = 20)
		public String getFamilyMemberOf()
			{
				return this.familyMemberOf;
			}
			
		public void setFamilyMemberOf(String familyMemberOf)
			{
				this.familyMemberOf = familyMemberOf;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "BadDebtDate", length = 23)
		public Date getBadDebtDate()
			{
				return this.badDebtDate;
			}
			
		public void setBadDebtDate(Date badDebtDate)
			{
				this.badDebtDate = badDebtDate;
			}
			
		@Column(name = "RejectionReasonAfterID", length = 10)
		public String getRejectionReasonAfterId()
			{
				return this.rejectionReasonAfterId;
			}
			
		public void setRejectionReasonAfterId(String rejectionReasonAfterId)
			{
				this.rejectionReasonAfterId = rejectionReasonAfterId;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastRejectionAfterDate", length = 23)
		public Date getLastRejectionAfterDate()
			{
				return this.lastRejectionAfterDate;
			}
			
		public void setLastRejectionAfterDate(Date lastRejectionAfterDate)
			{
				this.lastRejectionAfterDate = lastRejectionAfterDate;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "LastSKTDate", length = 23)
		public Date getLastSktdate()
			{
				return this.lastSktdate;
			}
			
		public void setLastSktdate(Date lastSktdate)
			{
				this.lastSktdate = lastSktdate;
			}
			
		@Column(name = "BiologicalMothersName", length = 50)
		public String getBiologicalMothersName()
			{
				return this.biologicalMothersName;
			}
			
		public void setBiologicalMothersName(String biologicalMothersName)
			{
				this.biologicalMothersName = biologicalMothersName;
			}
			
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
			
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
			
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
			
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
			
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
			
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
			
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
			
	}
