package com.adibrata.smartdealer.model;
// Generated Jul 18, 2015 2:43:49 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id; import javax.persistence.GeneratedValue; import javax.persistence.GenerationType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PettyCashHdr generated by hbm2java
 */
@Entity
@Table(name = "PettyCashHdr", catalog = "SmartDealer")
public class PettyCashHdr implements java.io.Serializable
	{
		
		private long id;
		private Employee employee;
		private Office office;
		private Partner partner;
		private String pcno;
		private Date postingDate;
		private Date valueDate;
		private Double pcamount;
		private Long jobId;
		private Date dtmUpd;
		private String usrUpd;
		private Date dtmCrt;
		private String usrCrt;
		private Set<PettyCashDtl> pettyCashDtls = new HashSet<PettyCashDtl>(0);
		
		public PettyCashHdr()
			{
			}
		
		public PettyCashHdr(long id)
			{
				this.id = id;
			}
		public PettyCashHdr(long id, Employee employee, Office office,
		        Partner partner, String pcno, Date postingDate, Date valueDate,
		        Double pcamount, Long jobId, Date dtmUpd, String usrUpd,
		        Date dtmCrt, String usrCrt, Set<PettyCashDtl> pettyCashDtls)
			{
				this.id = id;
				this.employee = employee;
				this.office = office;
				this.partner = partner;
				this.pcno = pcno;
				this.postingDate = postingDate;
				this.valueDate = valueDate;
				this.pcamount = pcamount;
				this.jobId = jobId;
				this.dtmUpd = dtmUpd;
				this.usrUpd = usrUpd;
				this.dtmCrt = dtmCrt;
				this.usrCrt = usrCrt;
				this.pettyCashDtls = pettyCashDtls;
			}
		
		@Id @GeneratedValue(strategy=GenerationType.AUTO)
		@Column(name = "ID", unique = true, nullable = false)
		public long getId()
			{
				return this.id;
			}
		
		public void setId(long id)
			{
				this.id = id;
			}
		
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "EmployeeID")
		public Employee getEmployee()
			{
				return this.employee;
			}
		
		public void setEmployee(Employee employee)
			{
				this.employee = employee;
			}
		
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "OfficeId")
		public Office getOffice()
			{
				return this.office;
			}
		
		public void setOffice(Office office)
			{
				this.office = office;
			}
		
		@ManyToOne(fetch = FetchType.LAZY)
		@JoinColumn(name = "PartnerCode")
		public Partner getPartner()
			{
				return this.partner;
			}
		
		public void setPartner(Partner partner)
			{
				this.partner = partner;
			}
		
		@Column(name = "PCNo", length = 50)
		public String getPcno()
			{
				return this.pcno;
			}
		
		public void setPcno(String pcno)
			{
				this.pcno = pcno;
			}
		
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "PostingDate", length = 23)
		public Date getPostingDate()
			{
				return this.postingDate;
			}
		
		public void setPostingDate(Date postingDate)
			{
				this.postingDate = postingDate;
			}
		
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "ValueDate", length = 23)
		public Date getValueDate()
			{
				return this.valueDate;
			}
		
		public void setValueDate(Date valueDate)
			{
				this.valueDate = valueDate;
			}
		
		@Column(name = "PCAmount", precision = 53, scale = 0)
		public Double getPcamount()
			{
				return this.pcamount;
			}
		
		public void setPcamount(Double pcamount)
			{
				this.pcamount = pcamount;
			}
		
		@Column(name = "JobId")
		public Long getJobId()
			{
				return this.jobId;
			}
		
		public void setJobId(Long jobId)
			{
				this.jobId = jobId;
			}
		
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmUpd", length = 16)
		public Date getDtmUpd()
			{
				return this.dtmUpd;
			}
		
		public void setDtmUpd(Date dtmUpd)
			{
				this.dtmUpd = dtmUpd;
			}
		
		@Column(name = "UsrUpd", length = 50)
		public String getUsrUpd()
			{
				return this.usrUpd;
			}
		
		public void setUsrUpd(String usrUpd)
			{
				this.usrUpd = usrUpd;
			}
		
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "DtmCrt", length = 16)
		public Date getDtmCrt()
			{
				return this.dtmCrt;
			}
		
		public void setDtmCrt(Date dtmCrt)
			{
				this.dtmCrt = dtmCrt;
			}
		
		@Column(name = "UsrCrt", length = 50)
		public String getUsrCrt()
			{
				return this.usrCrt;
			}
		
		public void setUsrCrt(String usrCrt)
			{
				this.usrCrt = usrCrt;
			}
		
		@OneToMany(fetch = FetchType.LAZY, mappedBy = "pettyCashHdr")
		public Set<PettyCashDtl> getPettyCashDtls()
			{
				return this.pettyCashDtls;
			}
		
		public void setPettyCashDtls(Set<PettyCashDtl> pettyCashDtls)
			{
				this.pettyCashDtls = pettyCashDtls;
			}
		
	}
