
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="../../Confins.css" rel="stylesheet" type="text/css">
</head>
<body>
<form runat="server" id="FrmAddAgreementBond">
<div align="center">
  <table width="95%" border="0" cellpadding="0" cellspacing="0">
    <tr> 
      <td colspan="3"><font color="red"><i>*) required field</i></font></td>
    </tr>
  </table>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr class="trtopikuning"> 
      <td width="10" height="20" class="tdtopitoscakiri">&nbsp;</td>
      <td align="center" class="tdtopitosca">AGREEMENT SELECTION FOR BOND</td>
      <td width="10" class="tdtopitoscakanan">&nbsp;</td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
	<tr> 
      <td width="200" class="tdgenap">Bank</td>
      <td class="tdganjil">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</td>
    </tr>

    <tr> 
      <td width="200" class="tdgenap">Funding Company Name</td>
      <td class="tdganjil">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</td>
    </tr>
   
    <tr> 
      <td class="tdgenap">Contract No</td>
      <td class="tdganjil">xxxxxxx20xxxxxx</td>
    </tr>
    <tr> 
      <td class="tdgenap">Contract Name</td>
      <td class="tdganjil">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</td>
    </tr>
    <tr> 
      <td class="tdgenap">Currency</td>
      <td class="tdganjil">xxx</td>
    </tr>
    <tr> 
      <td class="tdgenap"></td>
      <td class="tdganjil"></td>
    </tr>
    <tr> 
      <td class="tdgenap">Outstanding Loan</td>
      <td class="tdganjil">999,999,999</td>
    </tr>
    <tr> 
      <td class="tdgenap">Amount Must Be Add</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
    <tr> 
      <td class="tdgenap">Selected Principal Amt</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
    <tr>
      <td class="tdgenap">Selected A/R Amt</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
	<tr>
      <td class="tdgenap">Selected OTR Amount</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
	<tr>
      <td class="tdgenap">Selected Account</td>
      <td class="tdganjil">999</td>
    	</tr>
    <tr> 
      <td class="tdgenap">Security Percentage&nbsp; </td>
      <td class="tdganjil">xx % of xxxxx</td>
    </tr>
    <tr> 
      <td class="tdgenap">Current Security </td>
      <td class="tdganjil">&nbsp;</td>
    </tr>
    <tr> 
      <td class="tdgenap">Branch</td>
      <td class="tdganjil">
					<select name="Select1">
				<option>All</option>
				<option>Jakarta Elektronik</option>
			</select>		</td>
    </tr>
    <tr>
      <td class="tdgenap">Selected Principal Amt</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
	<tr>
      <td class="tdgenap">Selected A/R Amt</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
	<tr>
      <td class="tdgenap">Selected OTR Amount</td>
      <td class="tdganjil">999,999,999 </td>
    </tr>
	<tr>
      <td class="tdgenap">Selected Account</td>
      <td class="tdganjil">999</td>
    	</tr>
    <tr> 
      <td class="tdgenap" style="height: 42px">Currency Agreement</td>
      <td class="tdganjil" style="height: 42px"><select name="select">
          <option selected>IDR</option>
        </select></td>
    </tr>
    <tr> 
      <td class="tdgenap">Additonal Amount For This Branch&nbsp;</td>
      <td class="tdganjil"><input name="textfield332625" type="text" class="inptype" value="0" size="15"></td>
    </tr>
    </table>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr> 
      <td height="30">&nbsp; </td>
      <td align="right"> <a href="../DrawdownAgreementSelectionTL.htm">
		<a href="javascript:history.go(-1);"> 
        <img src="../../Images/ButtonCancel.gif" width="100" height="20" border="0"></a> 
      </td>
    </tr>
  </table>
</div>
</form>
</body>
</html>
