<%@ Page Language="VB" ContentType="text/html" ResponseEncoding="iso-8859-1" %>
<html>
<head>
<title>Untitled Document</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link href="../../Confins.css" rel="stylesheet" type="text/css">
</head>
<body>
<form runat="server" id="frmDrawdownReceiveFund">
<div align="center"> 
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr class="trtopikuning"> 
      <td width="10" height="20" class="tdtopitoscakiri">&nbsp;</td>
      <td align="center" class="tdtopitosca">DRAWDOWN FUND</td>
      <td width="10" class="tdtopitoscakanan">&nbsp;</td>
    </tr>
  </table>
  <table width="95%" border="0" cellpadding="2" cellspacing="1" class="tablegrid">
    <tr class="tdganjil"> 
      <td width="200" class="tdgenap">Funding Company Name</td>
      <td class="tdganjil">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Funding Company Branch</td>
      <td class="tdganjil"><a href="../FundingSourceView.htm">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</a></td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Facility No</td>
      <td><a href="../FundingSourceContractView.htm">xxxxxxx20xxxxxx</a></td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Facility Name</td>
      <td class="tdganjil">xxxxxxxxxxxxxx50xxxxxxxxxxxxxx</td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Batch No.</td>
      <td class="tdganjil"><a href="../DrawdownView.htm">xxxxxxx20xxxxxx</a> &nbsp;&nbsp;&nbsp;&nbsp; 
      </td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Drawdown Plan Date</td>
      <td class="tdganjil">dd/mm/yyyy</td>
    </tr>
    <tr class="tdganjil"> 
      <td class="tdgenap">Drawdown Amount</td>
      <td class="tdganjil">999,999,999,999</td>
    </tr>
    
    <tr> 
      <td class="tdgenap">Bank Account 1</td>
      <td class="tdganjil"><select name="select" style="width: 146px">
          <option selected>CitiBank</option>
        </select></td>
    </tr>
     <tr> 
      <td class="tdgenap">Amount For Bank Account 1</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>

    <tr> 
      <td class="tdgenap">Reference No For Bank Account 1</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>
 <tr> 
      <td class="tdgenap">Bank Account 2</td>
      <td class="tdganjil"><select name="select" style="width: 146px">
          <option selected>CitiBank</option>
        </select></td>
    </tr>
     <tr> 
      <td class="tdgenap">Amount For Bank Account 2</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>

    <tr> 
      <td class="tdgenap">Reference No For Bank Account 2</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>

 <tr> 
      <td class="tdgenap">Bank Account 3</td>
      <td class="tdganjil"><select name="select" style="width: 146px">
          <option selected>CitiBank</option>
        </select></td>
    </tr>
     <tr> 
      <td class="tdgenap">Amount For Bank Account 3</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>

    <tr> 
      <td class="tdgenap">Reference No For Bank Account 3</td>
      <td class="tdganjil">
		<input name="textfield33" type="text" class="inptype" size="15" style="width: 143px"></td>
    </tr>

    <tr class="tdganjil"> 
      <td class="tdgenap">Drawdown Date</td>
      <td class="tdganjil"><input name="textfield332" type="text" class="inptype" value="dd/mm/yyyy" size="15">
        <img src="../../Images/iconcalendar.gif" width="20" height="20" align="absmiddle"></td>
    </tr>
   
  </table>
  <table width="95%" border="0" cellspacing="0" cellpadding="0">
    <tr> 
      <td height="30">&nbsp;</td>
      <td align="right"> <a href="javascript:history.go(-1);">
		<img src="../../Images/ButtonSave.gif" width="100" height="20" border="0"> 
        <img src="../../Images/ButtonCancel.gif" width="100" height="20" border="0"></a> 
      </td>
    </tr>
  </table>
</div>
</form>
</body>
</html>
